/*
 FusionCharts JavaScript Library
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @version 3.10.1
*/
FusionCharts.register("module",["private","modules.renderer.js-gradientlegend",function(){function Z(c,g,p){var m=c[0],n=c[1];c=c[2];m+=(g[0]-m)*p;n+=(g[1]-n)*p;g=c+(g[2]-c)*p;return{hex:(ua+(m<<16|n<<8|g).toString(16)).slice(-6),rgb:[m,n,g]}}function ca(c,g){return c.maxvalue-g.maxvalue}function x(c){var g,p,m=c.colorRange||{},n=c.dataMin,x=c.dataMax,t=c.sortLegend||!1,l=c.mapByCategory||!1,A=c.defaultColor,b=c.numberFormatter,d=m.color;c=this.colorArr=[];var e,h,a;this.mapByCategory=l;"1"===m.mapbypercent&&
(this.mapbypercent=!0);if("1"===m.gradient&&!l){this.gradient=!0;p=Da($(m.startcolor,m.mincolor,m.code));t=ha(Da($(p,A,"CCCCCC")));l=this.scaleMin=H(m.startvalue,m.minvalue,this.mapbypercent?0:n);c.push({code:p,maxvalue:l,label:aa(m.startlabel),codeRGB:ha(p)});if(d&&(g=d.length))for(n=0;n<g;n+=1)A=d[n],p=Da($(A.color,A.code)),h=H(A.value,A.maxvalue),a=H(A.minvalue),h>l&&c.push({code:p,maxvalue:h,userminvalue:a,label:aa($(A.label,A.displayvalue)),codeRGB:ha(p)});c.sort(ca);g=c.length;for(n=1;n<g;n+=
1)A=c[n],p=A.maxvalue-l,0<p?(A.minvalue=l,A.range=p,l=A.maxvalue):(c.splice(n,1),--n,--g);2<=c.length&&(this.scaleMax=l,c[n-1].label=$(m.endlabel,c[n-1].label,c[n-1].displayvalue));1===c.length&&(h=H(m.maxvalue,this.mapbypercent?100:x),c.push({minvalue:l,maxvalue:h,range:h-l,label:m.endlabel}),this.scaleMax=h,delete c[0].code);m=c[0];x=c[c.length-1];m.code&&x.code||(p=fa(t),g=Ga((p[2]=0,p)),p=Ga((p[2]=100,p)),m.code||(m.codeRGB=g,m.code=ra(g)),x.code||(x.codeRGB=p,x.code=ra(p)));g=c.length;for(n=
1;n<g;n+=1)if(A=c[n],A.code){if(e)for(x=A,a=m.maxvalue,d=x.maxvalue-a;e<n;e+=1)t=c[e],p=Z(m.codeRGB,x.codeRGB,(t.maxvalue-a)/d),t.code=p.hex,t.codeRGB=p.rgb;e=null;m=A}else e=e||n;if(void 0===this.scaleMin||void 0===this.scaleMax)this.noValidRange=!0}else if(d&&(g=d.length)){for(n=0;n<g;n+=1)A=d[n],p=$(A.color,A.code),h=H(A.maxvalue),a=H(A.minvalue),e=$(A.label,A.displayvalue,l?W:b.dataLabels(a)+" - "+b.dataLabels(h)),(p&&h>a||l&&e)&&c.push({code:p,maxvalue:h,minvalue:a,label:aa(e),labelId:e.toLowerCase()});
c.length?t&&c.sort(ca):this.noValidRange=!0}}function X(c,g){return g?D(100*c)/100+"%":S(c,W).toString()}var ja=this,c=ja.hcLib,sa=ja.window,sa=/msie/i.test(sa.navigator.userAgent)&&!sa.opera,H=c.pluckNumber,ua=c.COLOR_BLACK,g=c.COLOR_GLASS,Ea=c.FC_CONFIG_STRING,va=c.graphics,Ga=va.HSBtoRGB,fa=va.RGBtoHSB,ra=va.RGBtoHex,ha=va.HEXtoRGB,ka=c.COMMASTRING,W=c.BLANKSTRING,aa=c.parseUnsafeString,Fa=c.graphics.convertColor,wa=c.POSITION_TOP,pa=c.POSITION_MIDDLE,xa=c.POSITION_START,Ha=c.POSITION_END,la=c.graphics.getDarkColor,
ga=c.graphics.getLightColor,$=c.pluck,S=c.getValidValue,qa=c.toRaphaelColor,Aa=c.hasTouch,D=Math.round,Q=Math.max,T=Math.min,Ia=Math.abs,P,Ja,Ba,Ka="rgba(192,192,192,"+(sa?.002:1E-6)+")",Da=function(c){return c&&c.replace(/^#?([a-f0-9]+)/ig,"$1")};x.prototype={getColorObj:function(c){var g=this.colorArr,p=this.gradient?1:0,m=g[p],n;if(this.mapByCategory){for(c=aa(c).toLowerCase();m;){if(m.labelId===c)return{code:m.code,seriesIndex:p};p+=1;m=g[p]}return{outOfRange:!0}}if(this.gradient){if(this.scaleMin<=
c&&this.scaleMax>=c){for(;m&&m.maxvalue<c;)p+=1,m=g[p];c=(c-m.minvalue)/m.range;return{code:Z(g[p-1].codeRGB,m.codeRGB,c).hex}}return{outOfRange:!0}}for(;m;){if(m.maxvalue>c&&m.minvalue<=c)return{code:m.code,seriesIndex:p};m.maxvalue===c&&(n=p);p+=1;m=g[p]}return(m=g[n])&&m.maxvalue===c?{code:m.code,seriesIndex:n}:{outOfRange:!0}}};x.prototype.constructor=x;c.colorRange=x;P=c.configureGradientLegendOptions=function(c,g){var p=c.legend,m=g.chart;p.legendSliderBorderWidth=H(m.legendpointerborderthickness,
1);p.legendSliderBorderColor=Fa($(m.legendpointerbordercolor,la("ABABAB",70)),H(m.legendpointerborderalpha,100));p.legendSliderWidth=H(m.legendpointerwidth,m.legendpointerswidth,12);p.legendSliderHeight=H(m.legendpointerheight,m.legendpointersheight,12);p.legendColorBoxBorderColor=p.borderColor;p.legendColorBoxBorderWidth=p.borderWidth;p.legendScaleColor=Fa($(m.legendscalelinecolor,ua),H(m.legendscalelinealpha,100));p.legendScalePadding=H(m.legendscalepadding,4);p.legendScaleLineThickness=H(m.legendscalelinethickness,
1);p.legendScaleTickDistance=H(m.legendscaletickdistance,6);p.itemStyle.cursor="default";p.interActivity=H(m.interactivelegend,1);p.legendSliderColor=Fa($(m.legendpointercolor,ga("ABABAB",50)),H(m.legendpointeralpha,100))};c.placeGLegendBlockRight=function(c,g,p,m,n){this.configureLegendOptions(c,g.chart,!0,n,p);P(c,g);n=this.snapLiterals||(this.snapLiterals={});var x=c[Ea],t=this.smartLabel||x.smartLabel,l=c.legend,A=c.chart.spacingRight,b,d,e=l.textPadding=2,h=2*e,a=l.title.padding,f=0,ia=0,k=2*
l.padding;g=H(g.chart.legendpadding,7)+l.borderWidth/2+1;var y=c.colorRange||{},z=y.colorArr,ma=y.mapbypercent,N=y.scaleMin,q=y.scaleMax-N,na=l.legendSliderWidth,w=l.legendSliderHeight/2;d=l.legendScalePadding;var s=l.legendScaleTickDistance,u=l.itemStyle||{};b=H(parseInt(u.lineHeight,10)||12);var v=.75*b,R=p-k,E,F,r=0,G,B,C,L,I,V,M;m-=k;if(!y.noValidRange&&z&&1<(F=z.length)){--F;l.title.text!==W&&(t.setStyle(l.title.style),b=t.getSmartText(l.title.text,R,Q(b,m/4)),l.title.text=b.text,f=b.width+k,
m-=ia=b.height+a);t.setStyle(u);b=t.lineHeight;R-=s+d+na;l.colorBoxX=na;a=Q(b,R/2);R=T(R-a-4,b);G=Q(b,m/2);E=m/4;s=z[0];s.scaleLabel=X(s.maxvalue,ma);b=t.getSmartText(s.label,E,R);s.label=b.text;u=b.height;s.labelY=v-b.height/2;d=t.getSmartText(s.scaleLabel,a,G);s.scaleLabel=d.text;y=d.height/2;B=d.width;s.scaleLabelY=v-d.height/2;l.colorBoxY=Q(y,b.width+h,w)+ia;s=M=z[F];s.scaleLabel=X(s.maxvalue,ma);b=t.getSmartText(s.label,E,R);s.label=b.text;u=Q(u,b.height);s.labelY=v-b.height/2;d=t.getSmartText(s.scaleLabel,
a,G);s.scaleLabel=d.text;B=Q(B,d.width);E=d.height/2;b=Q(b.width+h,E,w);s.scaleLabelY=v-d.height/2;l.colorBoxHeight=w=m-l.colorBoxY-b;G=w-E;C=w/q;I=T(w-r,G-y)-4;for(E=1;E<F;E+=1)s=z[E],L=(s.maxvalue-N)*C,b=t.getSmartText(s.label,2*T(L-r,w-L),R),s.label=b.text,u=Q(u,b.height),s.labelY=v-b.height/2,b=b.width/2,s.scaleLabel=X(s.maxvalue,ma),d=t.getSmartText(s.scaleLabel,a,2*T(L-y,G-L)),s.scaleLabel=d.text,B=Q(B,d.width),V=d.height/2,s.scaleLabelY=v-d.height/2,I=T(I,(L-Q(V+y,b+r)-4)*q/s.range),r=b+L,
y=V+L;I=Q(T(I,(T(G-y,w-r)-4)*q/M.range,.3*m),0);l.colorBoxHeight-=I;l.colorBoxWidth=u&&u+h||15;l.height=l.totalHeight=m+ia+k-I;l.width=(B&&B+e)+l.colorBoxWidth+na+l.legendScaleTickDistance+l.legendScalePadding+k;l.width<f&&(l.colorBoxX+=(f-l.width)/2,l.width=f);l.width>p&&(l.width=p);n.legendstartx=x.width-A-l.width;n.legendwidth=l.width;n.legendendx=n.legendstartx+n.legendwidth;n.legendheight=l.height;g+=l.width;c.chart.marginRight+=g;return g}l.enabled=!1;return 0};c.placeGLegendBlockBottom=function(c,
g,p,m,n){this.configureLegendOptions(c,g.chart,!1,n,p);P(c,g);n=this.snapLiterals||(this.snapLiterals={});var x=c[Ea],t=this.smartLabel||x.smartLabel,l=c.legend,A=c.chart,b=A.spacingBottom,d=A.spacingLeft,A=A.spacingRight,e,h,a=l.textPadding=2,f=l.title.padding,ia=0,k=0,y=2*l.padding;g=H(g.chart.legendpadding,7)+l.borderWidth/2+1;var z=c.colorRange||{},ma=z.colorArr,N=z.mapbypercent,q=z.scaleMin,na=z.scaleMax-q,w=l.legendSliderWidth,s=l.legendSliderHeight,u=l.legendScalePadding,v=l.legendScaleTickDistance,
R=l.itemStyle||{};e=H(parseInt(R.lineHeight,10)||12);var E=.75*e,F=m-y,r,G,B,C,L=0,I,V,M;p-=y;if(!z.noValidRange&&ma&&1<(G=ma.length)){--G;l.title.text!==W&&(t.setStyle(l.title.style),e=t.getSmartText(l.title.text,p,F/3),l.title.text=e.text,ia=e.width+y,F-=k=e.height+f);t.setStyle(R);e=t.lineHeight;F-=v+u+s;f=Q(e,F/2);R=T(F-f-4,e);r=p/4;C=2*r;B=ma[0];B.scaleLabel=X(B.maxvalue,N);e=t.getSmartText(B.label,r,R);B.label=e.text;F=e.height;B.labelY=E-e.height/2;h=t.getSmartText(B.scaleLabel,C,f);B.scaleLabel=
h.text;u=h.width/2;v=h.height;B.code||(B.code=$(l.minColor,"CCCCCC"));l.colorBoxX=Q(u,e.width+a,w);B=z=ma[G];B.scaleLabel=X(B.maxvalue,N);e=t.getSmartText(B.label,r,R);B.label=e.text;F=Q(F,e.height);B.labelY=E-e.height/2;h=t.getSmartText(B.scaleLabel,C,f);B.scaleLabel=h.text;v=Q(v,h.height);B=h.width/2;e=Q(e.width+a,B,w);l.colorBoxWidth=w=p-l.colorBoxX-e;C=w-B;I=w/na;M=T(w-L,C-u)-4;for(r=1;r<G;r+=1)B=ma[r],V=(B.maxvalue-q)*I,e=t.getSmartText(B.label,2*T(V-L,w-V),R),B.label=e.text,F=Q(F,e.height),
B.labelY=E-e.height/2,e=e.width/2,B.scaleLabel=X(B.maxvalue,N),h=t.getSmartText(B.scaleLabel,2*T(V-u,C-V),f),B.scaleLabel=h.text,v=Q(v,h.height),h=h.width/2,M=T(M,(V-Q(h+u,e+L)-4)*na/B.range),L=e+V,u=h+V;M=Q(T(M,(T(C-u,w-L)-4)*na/z.range,.3*p),0);l.colorBoxWidth-=M;l.width=p+y-M;l.width<ia&&(l.colorBoxX+=(ia-l.width)/2,l.width=ia);l.colorBoxY=k+s;l.colorBoxHeight=F&&F+2*a||15;l.height=l.totalHeight=(v&&v+a)+l.colorBoxHeight+k+s+l.legendScaleTickDistance+l.legendScalePadding+y;l.height>m&&(l.height=
m);n.legendstartx=d+.5*(x.width-d-A-l.width)+(l.x||0);n.legendwidth=l.width;n.legendendx=n.legendstartx+n.legendwidth;n.legendstarty=x.height-b-l.height;n.legendheight=l.height;n.legendendy=n.legendstarty+n.legendheight;g+=l.height;c.chart.marginBottom+=g;return g}l.enabled=!1;return 0};Ja=function(){return{point:this}};Ba=function(c){return D(100*c)/100};c.rendererRoot.drawGradientLegendItem=function(x){var P=this,p=P.paper,m=P.options,n=P.canvasLeft,U=P.canvasTop,t=P.canvasWidth,l=P.canvasHeight,
A=m.colorRange,b=m.chart.textDirection,d,e,h,a,f=m.legend,ia=H(f.padding,4),k=f.itemStyle,m=f.symbolStyle,y=f.interActivity,z=x.elements;x=z.elementGroup.trackTooltip(!0);var ma="vertical"===f.layout,N,q,na,w,s,u,v=0,R=f.lighting3d,E=f.colorBoxWidth,F=f.colorBoxHeight,r=E,G=F,B={FCcolor:{color:W,alpha:W,angle:0,ratio:W}},C=B.FCcolor,L=f.colorBoxX+ia,I=f.colorBoxY+ia,V,M,Na=f.legendColorBoxBorderColor,Oa=f.legendColorBoxBorderWidth,ya=["M"],da=f.legendScaleColor;s=f.legendScalePadding;var Z=f.legendScaleLineThickness,
T=Z%2/2;e=f.legendScaleTickDistance;var za=f.legendSliderWidth,X=f.legendSliderHeight;w=G/2;a=r/2;u=za/2;var ba=X/2,O,Ca,S,ta,Y;M=0;var ia=f.legendSliderColor,ca=f.legendSliderBorderColor,f=f.legendSliderBorderWidth;O=f%2/2;var aa,K={isFirst:!0},J={},oa,ea,ha,fa,ga={},la=!1;if(A&&(d=A.colorArr)&&1<(h=d.length)){K.toolText=oa=q=A.scaleMin;J.toolText=ea=A=A.scaleMax;na=A-q;K.snapPX=J.snapPX=0;K.tooltipConstraint=J.tooltipConstraint="chart";K.getLabelConfig=J.getLabelConfig=Ja;K.tooltipPos=[0,0];J.tooltipPos=
[0,0];J.tooltipOffsetReference=K.tooltipOffsetReference={};J.tooltipOffsetReference.left=K.tooltipOffsetReference.left+=n-20;J.tooltipOffsetReference.top=K.tooltipOffsetReference.top+=U;ha=z.colorBox=p.group("colorBox",x);if(ma){K.tooltipPos[0]=J.tooltipPos[0]=t+n;M=270;C.angle=90;n=L-za;t=L+r;U=I-ba;Ca=I+ba;n=D(L-za)+O;t=D(L)+O;U=D(I-ba)+O;Ca=D(I+ba)+O;l=D(L+r)+O;S=D(I-2)+O;ta=D(I+2)+O;Y=D(I)+O;N=L-u/2;V=D(N-ba)+O;N=D(N)+O;w=I-ba/2;u=D(w+ba)+O;w=D(w)+O;E/=2;O=["M",n,U,"L",t,U,t,S,l,Y,t,ta,t,Ca,n,
Ca,"Z","M",V,w,"L",N,w,"M",V,Y,"L",N,Y,"M",V,u,"L",N,u];w=L+r+s;l=D(w+e)+T;w=D(w)+T;V=L+a;t=h-1;for(e=0;e<h;e+=1)a=d[e],u=(a.maxvalue-q)/na,N=G*u+I,s=D(N)+T,e?(C.ratio+=ka,C.color+=ka,C.alpha+=ka,ya.push("L",w,s,l,s,"M",w,s),e===t?(ba=Ha,s=N+2):(ba=pa,s=N)):(ya.push(w,s,"L",l,s,"M",w,s),ba=xa,s=N-2),C.ratio+=100*(u-v),C.color+=$(a.code,ua),C.alpha+=$(a.alpha,100),v=u,a.legendItem=p.text(x).attr({text:a.label,x:V,y:s,"text-anchor":ba,direction:b,"vertical-align":pa}).rotate(M,V,s).css(k),a.legendSymbol=
p.text(x).attr({text:a.scaleLabel,x:l,y:N,"text-anchor":xa,direction:b,"vertical-align":pa}).css(k);K.xMin=J.xMin=0;K.xMax=J.xMax=0;J.yIni=K.yMin=J.yMin=0;K.yIni=K.yMax=J.yMax=G;K.x=J.x=0;K._oriY=K.y=0;J._oriY=J.y=G;b=X+r;d=za}else{K.tooltipPos[1]=J.tooltipPos[1]=l+U;n=D(L-u)+O;t=D(L+u)+O;U=D(I-X)+O;Ca=D(I+G)+O;l=D(L-2)+O;N=D(L+2)+O;V=D(L)+O;S=D(I)+O;ta=I-ba/2;Y=D(ta-ba)+O;ta=D(ta)+O;M=L-u/2;a=D(M+u)+O;M=D(M)+O;F/=2;O=["M",n,U,"L",t,U,t,S,N,S,V,Ca,l,S,n,S,"Z","M",M,Y,"L",M,ta,"M",V,Y,"L",V,ta,"M",
a,Y,"L",a,ta];s=I+G+s;M=D(s+e)+T;s=D(s)+T;N=I+w;t=h-1;for(e=0;e<h;e+=1)a=d[e],u=(a.maxvalue-q)/na,l=r*u+L,w=D(l)+T,e?(C.ratio+=ka,C.color+=ka,C.alpha+=ka,ya.push("L",w,s,w,M,"M",w,s),e===t?(ba=xa,w=l+2):(ba=pa,w=l)):(ya.push(w,s,"L",w,M,"M",w,s),ba=Ha,w=l-2),C.ratio+=100*(u-v),C.color+=$(a.code,ua),C.alpha+=$(a.alpha,100),v=u,a.legendItem=p.text(x).attr({text:a.label,x:w,y:N,"text-anchor":ba,direction:b,"vertical-align":pa}).css(k),a.legendSymbol=p.text(x).attr({text:a.scaleLabel,x:l,y:M,"text-anchor":pa,
direction:b,"vertical-align":wa}).css(k);J.xIni=K.xMin=J.xMin=0;K.xIni=K.xMax=J.xMax=r;K.yMin=J.yMin=0;K.yMax=J.yMax=0;K.y=J.y=0;K._oriX=K.x=0;J._oriX=J.x=r;b=za;d=X+G}c.rendererRoot.resetLegendSlider=function(){var a=ga[1],b=ga[0];a&&(aa(J.xMin,J.yMin,J.xMin-a.xChange,J.yMin-a.yChange,!0),la=!0);b&&(aa(K.xMax,K.yMax,K.xMax-b.xChange,K.yMax-b.yChange),la=!0)};z.colorBox=p.rect(ha).attr({x:L,y:I,width:r,height:G,fill:qa(B),stroke:Na,strokeWidth:Oa});R&&(z.colorBoxEffect=p.rect(ha).attr({x:L,y:I,width:E,
height:F,fill:g,"stroke-width":0}));z.scale=p.path(x).attr({path:ya,stroke:da,"stroke-width":Z});aa=function(a,b,d,e,c){var f;f=ga[+!!c]=ga[+!!c]||{};f.xChange=a;f.yChange=b;ma?(f=b*na/G+q,e=0<b?e:e+b+.01):(f=a*na/r+q,d=0<a?d:d+a+.01);a=Ba(f);c?(z.slider1.translate(d,e),z.slider1Tracker.toFront().translate(d,e).tooltip(a,null,null,!0),oa=f):(z.slider2.translate(d,e),z.slider2Tracker.toFront().translate(d,e).tooltip(a,null,null,!0),ea=f);y&&(fa=clearTimeout(fa),fa=setTimeout(function(){P.setScaleRange&&
P.setScaleRange(oa,ea)},100))};h=function(a,b){var d=0,e=d,c,f=this.isFirst,h=f?J:K;if(ma){e=this._startY+b;0>=e&&(e=0);e>G&&(e=G);if(f?e>h.y:e<h.y)e=h.y;Ia(e-this.y)>=(this.snapPX||0)&&(c=!0)}else{d=this._startX+a;0>=d&&(d=0);d>r&&(d=r);if(f?d>h.x:d<h.x)d=h.x;Ia(d-this.x)>=(this.snapPX||0)&&(c=!0)}c&&(aa(d,e,d-this.x,e-this.y,f),this.x=d,this.y=e)};R=function(){var a=this.isFirst,b=a?J:K;la&&(la=!1,this.x=b.xIni,this.y=b.yIni,b.x=b._oriX,b.y=b._oriY);this._startX=this.x;this._startY=this.y;this._scaleStart=
oa;this._scaleEnd=ea;ja.raiseEvent("LegendPointerDragStart",{pointerIndex:a?0:1,pointers:[{value:oa},{value:ea}],legendPointerHeight:X,legendPointerWidth:za},P.logic.chartInstance)};E=function(){var a=this._scaleStart,b=this._scaleEnd;ja.raiseEvent("LegendPointerDragStop",{pointerIndex:this.isFirst?0:1,pointers:[{value:oa},{value:ea}],legendPointerHeight:X,legendPointerWidth:za},P.logic.chartInstance);a===oa&&b===ea||ja.raiseEvent("LegendRangeUpdated",{previousMinValue:a,previousMaxValue:b,minValue:oa,
maxValue:ea},P.logic.chartInstance);delete this._scaleStart;delete this._scaleEnd};F=Ba(q);z.slider1=p.path(x).attr({path:O,fill:ia,"stroke-width":f,stroke:ca});Aa&&(n-=.5*(Q(30,b)-b),U-=.5*(Q(40,d)-d),b=Q(30,b),d=Q(40,d));z.slider1Tracker=p.rect(x).attr({ishot:!0,width:b,height:d,x:n,y:U,fill:Ka,stroke:"none"}).drag(h,R,E,K,K,K).tooltip(F,null,null,!0).css(m);F=Ba(A);z.slider2=p.path(x).attr({path:O,fill:ia,"stroke-width":f,stroke:ca}).translate(J.x,J.y);z.slider2Tracker=p.rect(x).attr({ishot:!0,
width:b,height:d,x:n,y:U,fill:Ka,stroke:"none"}).translate(J.x,J.y).css(m).drag(h,R,E,J,J,J).tooltip(F,null,null,!0)}}}]);
FusionCharts.register("module",["private","modules.renderer.js-maps",function(){var Z=this,ca=Z.window,x=Z.hcLib,X=x.chartAPI,ja=ca.document,c=x.pluck,sa=x.imprint,H=x.extend2,ua=x.parseTooltext,g=x.pluckNumber,Ea=x.pluckFontSize,va=x.HCstub,Ga=H(x.defaultPaletteOptions,{foregroundcolor:"333333",foregroundalpha:"100",foregrounddarkcolor:"111111",foregrounddarkalpha:"100",foregroundlightcolor:"666666",foregroundlightalpha:"100",backgroundlightcolor:"FFFFFF",backgroundlightalpha:"100",backgroundlightangle:90,
backgroundlightratio:"",backgroundcolor:"FFFFCC",backgroundalpha:"100",backgrounddarkcolor:"ffcc66",backgrounddarkalpha:"100",backgrounddarkangle:270,backgrounddarkratio:"",shadow:1}),fa=x.setLineHeight,ra=x.getValidValue,ha=x.parseUnsafeString,ka=x.getFirstColor,W=x.graphics.convertColor,aa=x.hashify,Fa=x.getDashStyle,wa=ca.navigator.userAgent,pa=/msie/i.test(wa)&&!ca.opera,xa=/AppleWebKit/.test(wa),Ha=/stroke/ig,la=x.hasSVG,ga=x.FC_CONFIG_STRING,$=ca.Math,S=$.min,qa=$.max,Aa=$.ceil,wa=!/fusioncharts\.com$/i.test(ca.location.hostname),
D=x.toRaphaelColor,Q={left:"start",right:"end",center:"middle"},T=function(b,d){var e;b||(b={});for(e in d)b[e]=d[e];return b},Ia=function(b){var d=this.parentNode;if(!d)return!1;for(;d&&d!==ja.documentElement;){if(d===b)return!0;d=d.parentNode}return!1},P=function(b,d){var e=d?T(b.FCcolor,d):{FCcolor:b};e.toString=D;return e},Ja=function(b,d){var e,c;this.index=d;for(c in b)e=Ga[b[c]],this[c]=e instanceof Array?e[d]:e},Ba={right:function(b,d){return d},left:function(b,d){return b-d},center:function(b,
d){return 2*S(d,b-d)}},Ka={top:function(b,d){return d},middle:function(b,d){return 2*S(d,b-d)},bottom:function(b,d){return b-d}},Da=function(b,d,e,c){d=S(b,d);b=.02*d;d*=.07;c=parseFloat(c);e=parseFloat(e);return isNaN(c)||isNaN(e)?isNaN(c)?isNaN(e)?{min:b,max:d}:{min:parseInt(e/10,10),max:e}:{min:c,max:10*c}:c<e?{min:c,max:e}:{min:e,max:c}},Ma=function(b){for(var d=b&&b.length||0,e={},c;d--;)c=b[d],void 0!==c.id&&(e[c.id.toLowerCase()]=c);return e},La=function(b,d){var e,c={};d=d||1;if(!b||"object"!==
typeof b)return c;for(e in b)Ha.test(e)||("stroke-width"===e?(c[e]=Number(b[e])/d,xa&&(c[e]=c[e]&&Aa(c[e])||0)):c[e]=b[e]);return c},p=function(){this.hoverEntity&&(x.raiseEvent.apply(x,this.hoverEntityEventArgs),delete this.hoverEntityEventArgs,this.hoverEntity&&this.hoverEntityAttr&&this.hoverEntity.attr(this.hoverEntityAttr),delete this.hoverEntityAttr,this.hoverEntity=null)},m=function(b,d){var e=b&&b.length||!1,c=d||"id",a={},f;if(!b)return b;for(;e--;)f=b[e],void 0!==f[c]&&(a[f[c].toLowerCase()]=
f);return a},n=function(b,d,e,c){function a(){var a=this,b=a.entityPathMap,d=a.data,e=a.items,c,d=Ma(d);u=function(){for(var g,h=b[c];h;)e[c]?a=null:((g=d[c])?g.mapItem=e[c]=new U(c,sa(f(g),h),q,a.group):e[c]=new U(c,h,q,a.group),c=h.nextId&&h.nextId.toLowerCase(),h=void 0!==c&&b[c]||null);l.call(a)};v=function(){var c,h,g=s,k,u=0;for(k in N)if(!e[k]&&(c=b[k],(h=d[k])?h.mapItem=e[k]=new U(k,sa(f(h),c),q,a.group):e[k]=new U(k,c,q,a.group),u+=1,delete N[k],u===g))break;u<m?(m-=u,setTimeout(v,0)):l.call(a)};
(c=z&&z.toLowerCase())?u():v()}function f(a){delete a.outlines;delete a.label;delete a.shortlabel;delete a.labelposition;delete a.labelalignment;delete a.labelconnectors;return a}function g(){var a=this.items,b=[],d,c={id:"entityLabels",items:b};for(d in a)a[d].drawLabel(b);n.addGroup(c)}function k(){var a=this.items,b;for(b in a)a[b].destroy();delete this.entityPathMap;delete this.data;delete this.chartObj;delete this.items;delete this.group}function l(){w.entities.labelsOnTop&&g.call(this);this.ready=
!0;q.checkComplete()}if(e&&e.getEntityPaths()){var z=e.getFirstId(),m=e.entityCount,N=e.getEntityPaths(!0),q=d,n=d.mapAnnotations,w=q.options,s=la?100:50,u,v,R;this.entityPathMap=N;this.data=b;this.chartObj=q;this.items={};this.ready=!1;this.group=c||d.mapGroup;this.isReady=function(){return this.ready};a.call(this);this.drawLabels=g;this.destroy=k;this.init=a;this.initComplete=l;q.__canvasMouseOutListenerAdded||(q.__canvasMouseOutListenerAdded=!0,R=d.paper.canvas,x.addEvent(R,"mouseout",function(a){a=
a.originalEvent.relatedTarget||a.originalEvent.toElement;!pa||la?a&&a.ownerSVGElement&&a.ownerSVGElement===R||p.call(q):a===ja.documentElement||a===d.container||a===d.container.parentElement?p.call(q):Ia.call(a,R)||p.call(q)}))}},U=function(b,d,e,h){function a(a){var b=this.featureConfig;return b&&"undefined"!==typeof b[a]?Boolean(b[a]):!1}function f(){var b;if(a.apply(this,["_ds"])){b=d.labels&&d.labels[0];if(!b)return;b=(r.useSNameInTooltip?b.shortText:b.text)+(isNaN(B)?"":r.tooltipSepChar+C)}else b=
(r.useSNameInTooltip?d.shortLabel:d.label)+(isNaN(B)?"":r.tooltipSepChar+C);return b}function l(a,b,e){b?e&&"undefined"!==typeof d.displayvalue?a=d.displayvalue:(a=c(r.includeNameInLabels?r.useShortName?a.shortText:a.text:""),r.includeValueInLabels&&!isNaN(B)&&(a=void 0===a?C:a+L+C)):a=a.text;return a}function k(a){for(var b=a&&a.length||0,d;b--;)d=a[b],this.connectorElem[b]=F.path(d,this.group).attr({transform:ea.transform,stroke:W(Q,T),"shape-rendering":"crisp","stroke-width":S})}function y(){var a=
this.chart.paper,b=la||!pa?"litepath":"path",d=this.eJSON.outlines,c=this.group,f,h,g;f=d&&d.length||0;if(this.hasFeature("_ds")){if(this.hasFeature("isDataEnabled"))if(K)for(;f--;)h=d[f].outline,this.svgElems[f]={},this.svgElems[f].graphic=a[b](h,c).attr(ea).tooltip(t).shadow(ka,e.shadowLayer);else for(;f--;)h=d[f].outline,this.svgElems[f]={},this.svgElems[f].graphic=a[b](h,c).tooltip(t).attr(ea);else if(K)for(;f--;)g=H(H({},ea),La(d[f].style,oa)),h=d[f].outline,this.svgElems[f]={},this.svgElems[f].graphic=
a[b](h,c).attr(g).tooltip(t).shadow(ka,e.shadowLayer);else for(;f--;)g=H(H({},ea),La(d[f].style,oa)),h=d[f].outline,this.svgElems[f]={},this.svgElems[f].graphic=a[b](h,c).tooltip(t).attr(g);this.hasFeature("isDataEnabled")&&this.addMouseGestures()}else{if(K)for(;f--;)h=d[f],this.svgElems[f]={},this.svgElems[f].graphic=a[b](h,c).attr(ea).tooltip(t).shadow(ka,e.shadowLayer);else for(;f--;)h=d[f],this.svgElems[f]={},this.svgElems[f].graphic=a[b](h,c).tooltip(t).attr(ea);this.addMouseGestures()}return this}
function z(a){var b=this.chart;b.hoverEntityEventArgs=["entityrollout",this.eventArgs,b.fusionCharts,[b.fusionCharts.id,"rollOut",this.legacyEventArgs],a];ca&&this.isVisible&&(b.hoverEntity=this,b.hoverEntityAttr=this.revertAttr,this.attr(this.hoverAttr));x.raiseEvent("entityrollover",this.eventArgs,b.fusionCharts,[b.fusionCharts.id,"rollOver",this.legacyEventArgs],a)}function m(a,b,d){var c=this,f=c.chart,h=a.labelPosition,g=a.labelAlignment,k=c.svgElems[0]&&c.svgElems[0].graphic,u=a.style,r,v,y,
s,q;h?(k=h[0],h=h[1]):(h=k.getBBox(),k=h.x+h.width/2,h=h.y+h.height/2);g?(r=g[0],g=g[1],"right"===r?k-=U:"left"===r&&(k+=U),"top"===g?h-=U:"bottom"===g&&(h+=U)):(r="center",g="middle");v=O;y=parseFloat(ba)/e.sFactor;s=X;q=fa;!b&&u&&(u.color&&(v=u.color),u["font-size"]&&(y=parseFloat(u["font-size"])/e.sFactor),u["font-family"]&&(s=u["font-family"]),void 0!==u["font-weight"]&&(q="bold"===u["font-weight"]));return{x:k.toString(),y:h.toString(),wrapwidth:Ba[r](ra,k+va)-U,wrapheight:Ka[g](sa,h+wa)-U,wrap:1,
type:"text",align:r,valign:g,text:l(a,b,d),tooltext:t,link:ja,bgcolor:"",bordercolor:"",fillcolor:v,fontsize:y,font:s,bold:q,onclick:function(a){Z.raiseEvent("entityclick",c.eventArgs,e.fusionCharts,a)},onmouseover:function(a){c!==f.hoverEntity&&(p.call(c.chart),z.call(c,a))},ontouchstart:function(a){c!==f.hoverEntity&&(p.call(c.chart),z.call(c,a))}}}function N(a){var b=this.eJSON,d=this.hasFeature("isDataEnabled"),c,e;if(!ya)return null;if(this.hasFeature("_ds"))for(e=(b=b.labels)&&b.length||0;e--;)c=
b[e],a.push(this.getLabelObject(c,d,!e)),c.labelConnectors&&this.drawLabelConnectors(c.labelConnectors);else c={text:b.label,shortText:b.shortLabel,labelAlignment:b.labelAlignment,labelPosition:b.labelPosition},a.push(this.getLabelObject(c,!0,!0)),b.labelConnectors&&this.drawLabelConnectors(b.labelConnectors)}function q(a,b){var d=this.svgElems,c;for(c in d)d[c].graphic&&d[c].graphic.attr(a,b)}function n(){var a=this.svgElems,b;this.isVisible=!0;for(b in a)a[b].graphic&&a[b].graphic.attr(ea)}function w(){var a=
this.svgElems,b=this.chart,d;this.isVisible=!1;b.hoverEntity===this&&p.call(b);for(d in a)a[d].graphic&&a[d].graphic.attr(J)}function s(a){Z.raiseEvent("entityclick",this.node.__entity.eventArgs,e.fusionCharts,a);void 0!==ja&&e.logic.linkClickFN.call({link:ja})}function u(a){var b=this.node.__entity,d=b.chart;b!==d.hoverEntity&&(p.call(d),z.call(b,a))}function v(){var a=this.eJSON,b=this.svgElems,d;this.eventArgs={value:this.value,label:a.label,shortLabel:a.shortLabel,originalId:this.originalId||
this.id,id:this.id};this.legacyEventArgs={value:this.value,lName:a.label,sName:a.shortLabel,id:this.originalId||this.id};ca&&(this.hoverAttr={fill:this.hoverColor.toString()},this.revertAttr={fill:this.fillColor.toString()},Y!==da&&(this.hoverAttr["stroke-width"]=Y,this.revertAttr["stroke-width"]=da));if(!isNaN(B)||aa)for(d in b)void 0!==ja&&b[d].graphic.css({cursor:"pointer",_cursor:"hand"}),b[d].graphic.node.__entity=this,b[d].graphic.click(s).hover(u)}function R(){var a=this.svgElems,b=this.connectorElem,
d;for(d in a)a[d].remove&&a[d].remove();for(d in b)b[d].destroy&&b[d].destroy();delete this.value;delete this.formattedValue;delete this.toolText;delete this.fillColor;delete this.hoverColor;delete this.chart;delete this.group;delete this.id;delete this.isVisible;delete this.svgElems;delete this.connectorElem;delete this.renderer;delete this.options}if(d&&e&&void 0!==b){this.chart=e;this.eJSON=d;this.group=h;this.id=b;this.originalId=d.origId;this.isVisible=!0;this.svgElems={};this.connectorElem=
{};this.featureConfig=d.options;"object"===typeof this.featureConfig&&(this.featureConfig._ds=!0);var E=e.options,F=e.paper,r=E.entities,G=r.dataLabels.style;b=d.cleanValue;var B=null===b?void 0:b,C=this.formattedValue=d.formattedValue||"",L=r.labelSepChar,I=g(d.showtooltip,r.showTooltip);b=f.call(this);h={formattedValue:C,sName:d.shortLabel,lName:d.label};var t=I?ha(c(ua(c(d.tooltext,r.tooltext,b),[1,2,7,38,39],h,d))):"",M,A,D,ya=g(d.showlabel,r.showLabels);h=c(d.bordercolor,r.borderColor);b=c(d.borderalpha,
r.borderAlpha);var I=1===r.scaleBorder,da=g(d.borderthickness,r.borderThickness),Q=c(d.labelconnectorcolor,r.connectorColor),T=c(d.labelconnectoralpha,r.connectorAlpha),S=g(d.labelconnectorthickness,r.connectorThickness),X=c(d.font,G.fontFamily),ba=g(parseInt(d.fontsize,10),parseInt(G.fontSize,10)),O=c(d.fontcolor,G.color),U=g(d.labelpadding,r.labelPadding),aa=r.hoverOnNull,ca=g(d.showhovereffect,d.usehovercolor,aa?r.showHoverEffect:isNaN(B)?0:r.showHoverEffect),Y=g(d.borderhoverthickness,d.hoverborderthickness,
r.hoverBorderThickness),fa=g(d.fontbold,0),ja=d.link,K=r.shadow;D=!pa||la;G=e.sFactor/r.baseScaleFactor;M=e.strokeWidth;A=(D?r.baseScaleFactor:1)*M;var J=r.hiddenEntityFillObject||(r.hiddenEntityFillObject={fill:P({color:r.hiddenEntityColor,alpha:r.hiddenEntityAlpha}).toString()}),oa,ea,ka,E=E[ga],ra=E._labelBaseWidth,sa=E._labelBaseHeight,va=E._labelXOffset,wa=E._labelYOffset;D?(da=I?da*A:da/G,S/=G,oa=I?G:e.sFactor,xa&&(da=da&&Aa(da)||0,S=S&&Aa(S)||0)):(da=I?da*M:da,oa=I?e.scaleFactor:r.baseScaleFactor);
r.showHiddenEntityBorder||(J["stroke-width"]=0);void 0===Y?Y=da:D?(Y=I?da*A:Y/G,xa&&(Y=Y&&Aa(Y)||0)):Y=I?Y*M:Y;!r.showNullEntityBorder&&isNaN(B)&&(da=0);void 0!==c(d.color,d.alpha,d.angle,d.ratio)?(I=c(d.color,r.fillColor),E=c(d.alpha,r.fillAlpha),M=c(d.angle,r.fillAngle),A=c(d.ratio,r.fillRatio),D=P({color:I,alpha:E,angle:M,ratio:A})):(r.fillColorObject||(r.fillColorObject=P({color:c(r.fillColor),alpha:c(r.fillAlpha),angle:c(r.fillAngle),ratio:c(r.fillRatio)})),r.emptyColorObject||(r.emptyColorObject=
P({color:c(r.nullEntityColor),alpha:c(r.nullEntityAlpha),angle:c(r.nullEntityAngle),ratio:c(r.nullEntityRatio)})),D=isNaN(B)?r.emptyColorObject:r.fillColorObject,I=D.FCcolor.color,E=D.FCcolor.alpha,M=D.FCcolor.angle,A=D.FCcolor.ratio);""===t&&(I=0);ea={transform:la||!pa?"":e.transformStr,stroke:W(h,b),"stroke-width":da,fill:(this.fillColor=D).toString()};h=E.split(",");da&&h.push(b);ka={scalefactor:[G,e.sFactor],opacity:qa.apply($,h)/100};ca&&(void 0!==c(d.fillhovercolor,d.fillhoveralpha,d.fillhoverangle,
d.fillhoverratio,d.hoverfillcolor,d.hoverfillalpha,d.hoverfillratio,d.hoverfillangle)?(I=c(d.fillhovercolor,d.hoverfillcolor,r.hoverFillColor),E=c(d.fillhoveralpha,d.hoverfillalpha,r.hoverFillAlpha),M=c(d.fillhoverangle,d.hoverfillangle,r.hoverFillAngle),A=c(d.fillhoverratio,d.hoverfillratio,r.hoverFillRatio),b=P({color:I,alpha:E,angle:M,ratio:A})):(r.hoverColorObject||(r.hoverColorObject=P({color:r.hoverFillColor,alpha:r.hoverFillAlpha,angle:r.hoverFillAngle,ratio:r.hoverFillRatio})),b=r.hoverColorObject),
this.hoverColor=b);this.value=B;this.addMouseGestures=v;this.attr=q;this.draw=y;this.drawLabel=N;this.getLabelObject=m;this.destroy=R;this.show=n;this.hide=w;this.hasFeature=a;this.drawLabelConnectors=k;y.call(this);r.hideNullEntities&&void 0===B&&this.hide()}},t=function(b,d,c,h){this.id=b;this.definition=d;this.application=c;this.rapi=h;this.markerLabel=this.markerShape=this.label=this.options=this.value=this.hasValue=null;this.drawOptions={shape:null,label:null};this.drawComplete=!1;if(b=h.options)this._conf=
b[ga];this.init()},l=function(b,d,c,h){this.options=b;this.from=d;this.to=c;this.api=h;if(b=h.options)this._conf=b[ga]},A=function(b,d){function e(){var b=z.definition,c=m(b)||{},e=m(z.application)||{},h=z.shapes,g,k;if(b&&b.length){if(h&&h.length)for(b=h.length;b;--b)if(g=h[b-1],k=g.id.toLowerCase())a[k]=g;for(k in c){g=c[k];h=new t(k,g,e[k],d);if(b=h.getShapeId())h.shapeObj=a[b];f[k]=h}}}function h(){var b=z.items,c=z.shapes,e,h,g,k;if(b&&b.length){if(c&&c.length)for(e=c.length;e;--e)if(h=c[e-1],
k=h.id.toLowerCase())a[k]=h;for(e=b.length;e--;)if(h=b[e],k=h.id&&h.id.toLowerCase())void 0!==h.value&&""!==h.value&&parseFloat(h.value),h.mapItem=c=new t(k,h,null,d),g=c.getShapeId(),h.__hideMarker&&(c._isHidden=!0),g&&(c.shapeObj=a[g]),f[k]=c}}var a={},f={},g=[],k=d.options.markers,y=d.options.connectors,z=b,p=d.mapAnnotations,N,q,n,w,s=[];this.items=f;(function(){var a=t.prototype,b=l.prototype,e;e=Boolean(c(k.hoverFillColor,k.hoverFillAlpha,k.hoverFillAngle,k.hoverFillRatio,k.hoverBorderThickness,
k.hoverBorderColor,k.hoverBorderAlpha));a.markerFont=k.dataLabels.style.fontFamily;a.markerFontSize=k.dataLabels.style.fontSize;a.markerFontColor=k.dataLabels.style.fontColor;a.showMarkerTooltip=k.showTooltip;a.showHoverEffect=e;a.tooltext=k.tooltext;a.showMarkerLabels=k.showLabels;a.markerLabelPadding=k.labelPadding;a.labelWrapWidth=k.labelWrapWidth;a.labelWrapHeight=k.labelWrapHeight;a.labelSepChar=k.labelSepChar;a.tooltipSepChar=k.tooltipSepChar;a.fillColor=k.fillColor;a.fillAlpha=k.fillAlpha;
a.fillRatio=k.fillRatio;a.fillAngle=k.fillAngle;a.hoverFillColor=k.hoverFillColor;a.hoverFillAlpha=k.hoverFillAlpha;a.hoverFillRatio=k.hoverFillRatio;a.hoverFillAngle=k.hoverFillAngle;a.startAngle=k.startAngle;a.shapeId=k.shapeId;a.borderThickness=k.borderThickness;a.borderColor=k.borderColor;a.borderAlpha=k.borderAlpha;a.hoverBorderThickness=k.hoverBorderThickness;a.hoverBorderColor=k.hoverBorderColor;a.hoverBorderAlpha=k.hoverBorderAlpha;a.markerRadius=k.radius;a.autoScale=k.autoScale?d.sFactor:
1;a.shadow=k.shadow;a.applyAll=k.applyAll;a.dataEnabled=k.dataEnabled;a.valueToRadius=k.valueToRadius;a=Boolean(c(y.hoverthickness,y.hovercolor,y.hoveralpha));b.showHoverEffect=a;b.showTooltip=y.showTooltip;b.tooltext=y.tooltext;b.thickness=y.thickness;b.color=y.color;b.alpha=y.alpha;b.hoverThickness=y.hoverthickness;b.hoverColor=y.hovercolor;b.hoverAlpha=y.hoveralpha;b.dashed=y.dashed;b.dashlen=y.dashLen;b.dashgap=y.dashGap;b.font=y.font;b.fontsize=y.fontSize;b.fontcolor=y.fontColor;b.bgcolor=y.labelBgColor;
b.bordercolor=y.labelBorderColor;b.shadow=y.shadow;b.hideOpen=y.hideOpen})();k.dataEnabled?h():e();(function(){var b=f,d=[],c,e,h,g;q=p.addGroup({items:[]});N=p.addGroup({fillalpha:"100",items:d});for(g in b)c=null,e=b[g],h=e.getShapeId(),e&&!e._isHidden&&(h&&(e.shapeObj=a[h]),c=e.draw()),c&&(e._annotationIndex=d.length,e.markerShape=c.markerShape&&N.addItem(c.markerShape),e.markerLabel=c.markerLabel&&q.addItem(c.markerLabel))})();(function(){var a=y.showLabels,b=z.connectors,c=b&&b.length,e=[],h=
[],k,q,p;if(c)for(s.push({id:"connectorLabels",fillalpha:"100",items:h}),s.push({id:"connectors",fillalpha:"100",items:e});c--;)if(p=b[c],p.from&&p.to&&(k=f[p.from.toLowerCase()],q=f[p.to.toLowerCase()],k&&q&&(!y.hideOpen||!k._isHidden&&!q._isHidden)&&(g.push(q=new l(p,k,q,d)),q.connectJSON=k=q.computeConnectorJSON())))e.push(k),k.label&&a&&h.push(q.getLabelJSON())})();w=s.length;for(d.internalAnnotations={};w--;)n=s.shift(),n.id?d.internalAnnotations[n.id]=p.addGroup(n):p.addGroup(n);this.addMarkerItem=
function(b){var c,e;if((c=b.id.toLowerCase())&&!f[c]){delete b.value;b=new t(c,b,null,d);if(e=b.getShapeId())b.shapeObj=a[e];f[c]=b;c=b.draw();N&&q&&(b.markerShape=c.markerShape&&N.addItem(c.markerShape,!0),b.markerLabel=c.markerLabel&&q.addItem(c.markerLabel,!0))}}};l.prototype={constructor:l,computeConnectorJSON:function(){var b=this.api,d=this.options,e=this.from,h=this.to,a=d.link,f=d.label,l=g(d.showtooltip,this.showTooltip),k=l?c(d.tooltext,this.tooltext):"",y=c(d.thickness,this.thickness),
z=c(d.color,this.color),m=c(d.alpha,this.alpha),n=g(d.showhovereffect,this.showHoverEffect),q=c(d.hovercolor,this.hoverColor,z),x=c(d.hoveralpha,this.hoverAlpha,m),w=c(d.hoverthickness,this.hoverThickness,y),s=c(d.dashed,this.dashed),u=g(d.dashlen,this.dashlen),v=g(d.dashgap,this.dashgap),t;k&&(this.tooltext=k=ha(ua(k,[3,40,41,42,43],{label:f,fromId:e.definition.id,toId:h.definition.id,fromLabel:e.definition.label,toLabel:h.definition.label},d)));return e&&h?(t={fromMarkerId:e.id,toMarkerId:h.id,
label:f},H({type:"line"},{x:e.definition.x,y:e.definition.y,tox:h.definition.x,toy:h.definition.y,dashed:s,dashlen:u,dashgap:v,link:a,tooltext:l?k:"",thickness:y,color:z,alpha:m,label:f,showshadow:this.shadow,_hovereffect:n,_defaultattrs:{stroke:P({color:z,alpha:m}).toString(),"stroke-width":y},_hoverattrs:{stroke:P({color:q,alpha:x}).toString(),"stroke-width":w},onmouseover:function(a){var d=a.data,c=d.wrapper;c&&d.options._hovereffect&&(p.call(b),c.attr(d.options._hoverattrs));Z.raiseEvent("connectorrollover",
t,b.fusionCharts,a)},onmouseout:function(a){var d=a.data,c=d.wrapper;c&&d.options._hovereffect&&c.attr(d.options._defaultattrs);Z.raiseEvent("connectorrollout",t,b.fusionCharts,a)},onclick:function(a){Z.raiseEvent("connectorClick",t,b.fusionCharts,a)}})):null},getLabelJSON:function(){var b=this.connectJSON;return H({type:"text"},{x:((Number(b.x)+Number(b.tox))/2).toString(),y:((Number(b.y)+Number(b.toy))/2).toString(),text:b.label,align:"center",valign:"middle",font:this.font,fontsize:this.fontsize/
this.api.sFactor,fillcolor:this.fontcolor,bgcolor:this.bgcolor,bordercolor:this.bordercolor,tooltext:this.tooltext})}};t.prototype={constructor:t,init:function(){var b;b=this.options=H({},this.definition);this.dataEnabled?isNaN(b.value)||""===b.value||(this.value=parseFloat(b.value),this.hasValue=!0):this.applyAll?this.options=H(b,this.application):this.application&&(this.options=H(b,this.application))},getShapeId:function(){return this.options.shapeid&&this.options.shapeid.toLowerCase()||this.shapeId},
getLabelOptions:function(b,d,c,h,a){var f,g=b&&b.toLowerCase();this.getLabelAlignment[g]||(g="center");b=Number(c.x);f=Number(c.y);c=void 0===h||void 0===a?c.radius||0:/^(top|bottom)$/ig.test(g)&&.5*a||/^(left|right)$/ig.test(g)&&.5*h||0;c=Number(c)+Number(d);return this.getLabelAlignment[g](b,f,c)},draw:function(){if(this.options){var b=this,d=b.rapi,e=b._conf,h=d.translateX,a=d.translateY,f=b.options,l=b.getShapeId(),k=f.scale||1,y=f.label||"",z=(f.labelpos||"top").toLowerCase(),m=void 0===f.formattedValue?
void 0:f.formattedValue,n=f.tooltext||b.tooltext,q=g(f.radius,b.markerRadius)*k*b.autoScale||1E-4,x=c(f.fillcolor,f.color,b.fillColor),w=c(f.fillalpha,f.alpha,b.fillAlpha),s=c(f.fillratio,b.fillRatio),u=c(f.fillangle,b.fillAngle),v=g(f.borderthickness,b.borderThickness),t=c(f.bordercolor,b.borderColor),E=c(f.borderalpha,b.borderAlpha),F=f.labelpadding||b.markerLabelPadding,r,G;if(l){n=n?ha(ua(n,[1,2,3],{formattedValue:m,label:y},f)):m?y+b.tooltipSepChar+m:y;void 0!==m&&null!==m?y=y+b.labelSepChar+
m:isNaN(k)?k=1:0>k?k=0:5<k&&(k=5);r=function(){var c=b.markerShape,e=c.options,f=c.bounds,g=e._markerEventArgs;(c=c.wrapper)&&e.hovereffect&&(p.call(d),c.attr(e._hoverattrs));g||(g=e._markerEventArgs={x:f.x1/f.xs,y:f.y1/f.ys,scaledX:f.x1,scaledY:f.y1,chartX:h+f.x1,chartY:a+f.y1,id:e._markerId,label:e._markerLabel});Z.raiseEventGroup(b.id,"markerRollOver",g,d.fusionCharts,b,void 0,void 0,void 0)};G=function(){var a=b.markerShape,c=a.wrapper;c&&a.options.hovereffect&&c.attr(a.options._defaultattrs);
Z.raiseEventGroup(b.id,"markerRollOut",a.options._markerEventArgs,d.fusionCharts,void 0,void 0,void 0)};f={x:f.x.toString(),y:f.y.toString(),fillcolor:x,fillalpha:w,fillratio:s,fillangle:u,borderthickness:v,bordercolor:t,borderalpha:E,hovereffect:c(f.showhovereffect,b.showHoverEffect),radius:q.toString(),tooltext:b.showMarkerTooltip?n:"",link:f.link,showshadow:g(f.showshadow,b.shadow),_markerLabel:y,_markerId:f.id,id:(f.id+"").toLowerCase(),onmouseover:function(){r()},onmouseout:function(){G()},onclick:function(a){Z.raiseEvent("markerClick",
a.data.options._markerEventArgs,d.fusionCharts,a)}};"triangle"===l?H(f,{type:"polygon",sides:3,startangle:b.startAngle}):"diamond"===l?H(f,{type:"polygon",sides:4,startangle:b.startAngle}):"arc"===l?H(f,{type:"arc",startangle:0,endangle:360,innerradius:.6*q}):"circle"===l?f.type="circle":(F=b.getShapeArgs(),b.dataEnabled&&b.valueToRadius&&void 0!==f.radius?delete F.radius:(!F.radius&&(F.radius=b.markerRadius),F.radius=F.radius*k*b.autoScale),H(f,F));H(f,{hoverfillcolor:c(f.fillhovercolor,b.hoverFillColor,
f.fillcolor),hoverfillalpha:c(f.fillhoveralpha,b.hoverFillAlpha,f.fillalpha),hoverfillratio:c(f.fillhoverratio,b.hoverFillRatio,f.fillratio),hoverfillangle:c(f.fillhoverangle,b.hoverFillAngle,f.fillangle),hoverborderthickness:g(f.borderhoverthickness,b.hoverBorderThickness,f.borderthickness),hoverbordercolor:c(f.borderhovercolor,b.hoverBorderColor,f.bordercolor),hoverborderalpha:c(f.borderhoveralpha,b.hoverBorderAlpha,f.borderalpha)});f._defaultattrs={fill:P({alpha:f.fillalpha,color:f.fillcolor,angle:f.fillangle,
ratio:f.fillratio}).toString(),"stroke-width":"0"!==f.showborder?f.borderthickness:0,stroke:W(f.bordercolor,f.borderalpha)};f._hoverattrs={fill:P({alpha:f.hoverfillalpha,color:f.hoverfillcolor,angle:f.hoverfillangle,ratio:f.hoverfillratio}).toString(),"stroke-width":"0"!==f.showborder?f.hoverborderthickness:0,stroke:W(f.hoverbordercolor,f.hoverborderalpha)};"image"===f.type&&(f.borderthickness=f.borderthickness||0,f.onload=function(a){var b=this.options,c=a.width;a=a.height;var e=(Number(b.x)-c/(2*
d.sFactor))*d.sFactor,b=(Number(b.y)-a/(2*d.sFactor))*d.sFactor,f;if(c&&a)for(f in{wrapper:1,tracker:1})this[f]&&this[f].attr({x:e,y:b,width:c,height:a})});b.drawOptions.shape=f;if(!b.showMarkerLabels)return{markerShape:f};F=f.labelpadding||b.markerLabelPadding;k=b.getLabelOptions(z,F,f);z=k.align;l=k.valign;n=e._labelBaseWidth;m=e._labelBaseHeight;q=e._labelXOffset;e=e._labelYOffset;n=b.labelWrapWidth?b.labelWrapWidth:b.getWrapWidth[z](n,Number(k.x)+q);e=b.labelWrapHeight?b.labelWrapHeight:b.getWrapHeight[l](m,
Number(k.y)+e);n>F&&(n-=F);e>F&&(e-=F);b.drawOptions.label="center"==z&&"middle"==l?H({type:"text"},{text:y,tooltext:f.tooltext,x:k.x,y:k.y,align:z,valign:k.valign,wrap:1,wrapwidth:n,wrapheight:e,fontsize:b.markerFontSize/d.sFactor,font:b.markerFont,fillcolor:b.markerFontColor,onmouseover:function(){r()},onmouseout:function(){G()}}):H({type:"text"},{text:y,tooltext:f.tooltext,x:k.x,y:k.y,align:z,valign:k.valign,wrap:1,wrapwidth:n,wrapheight:e,fontsize:b.markerFontSize/d.sFactor,font:b.markerFont,
fillcolor:b.markerFontColor});return{markerShape:f,markerLabel:b.drawOptions.label}}}},show:function(){this.setMarkerVisibility(!0)},hide:function(){this.setMarkerVisibility(!1)},setMarkerVisibility:function(b){var d=this.rapi&&this.rapi.internalAnnotations;if(d=(d=d&&d.markers)&&d.items)if(d=d[this._annotationIndex])this._origFill||(this._origFill=P({alpha:d.fillAlpha,color:d.fillColor,angle:d.fillAngle,ratio:d.fillRatio}),this._hideFill=P({alpha:"0",color:d.fillColor,angle:d.fillAngle,ratio:d.fillRatio})),
b?d.wrapper.attr({fill:this._origFill}):d.wrapper.attr({fill:this._hideFill})},getShapeArgs:function(){var b=H({},this.shapeObj),d;return b?("polygon"===b.type?3>b.sides?b.type="circle":b.startangle=this.startAngle:"arc"===b.type&&(d=(b.radius||this.markerRadius)*this.autoScale,b.radius=d,b.innerradius=b.innerradius&&b.innerradius*this.autoScale||.6*d),b):null},destroy:function(){var b=this.markerShape,d=this.markerLabel,c;b&&b.destroy();d&&d.destroy();for(c in this)delete this[c]},getLabelAlignment:{top:function(b,
d,c){return{x:b.toString(),y:(d-c).toString(),align:"center",valign:"top"}},left:function(b,d,c){return{x:(b-c).toString(),y:d.toString(),align:"right",valign:"middle"}},right:function(b,d,c){return{x:(b+c).toString(),y:d.toString(),align:"left",valign:"middle"}},bottom:function(b,d,c){return{x:b.toString(),y:(d+c).toString(),align:"center",valign:"bottom"}},center:function(b,d){return{x:b.toString(),y:d.toString(),align:"center",valign:"middle"}}},getWrapWidth:{right:function(b,d){return d},left:function(b,
d){return b-d},center:function(b,d){return 2*S(d,b-d)}},getWrapHeight:{top:function(b,d){return d},middle:function(b,d){return 2*S(d,b-d)},bottom:function(b,d){return b-d}}};T(x.eventList,{entityrollover:"FC_Event",entityrollout:"FC_Event"});X("geo",{name:"geo",friendlyName:"Map",revision:1,creditLabel:wa,standaloneInit:!1,annotationInteractionEvents:!1,charttopmargin:10,chartrightmargin:10,chartbottommargin:10,chartleftmargin:10,baseWidth:400,baseHeight:300,baseScaleFactor:1,defaultSeriesType:"geo",
rendererId:"maps",entities:{},draw:function(b,d){var c=this.renderer,h=this.chartInstance;c||(c=this.renderer=new X("renderer."+this.rendererId));this.updateDefaultAnnotations();h.addEventListener("internal.mapdrawingcomplete",function(a,b){d&&d.apply(this,[b.renderer]);a.detachHandler()});return c.init(this,b,function(a){a.checkComplete()})},chart:function(b,d){H(this.dataObj.chart,{charttopmargin:this.dataObj.chart.maptopmargin,chartrightmargin:this.dataObj.chart.maprightmargin,chartbottommargin:this.dataObj.chart.mapbottommargin,
chartleftmargin:this.dataObj.chart.mapleftmargin,animation:this.dataObj.chart.animation||"0"});var e=this.dataObj,h=va(e,b,d,this),a=e.chart,f=e.markers,l=h.chart,k=h[ga],y=l.useRoundEdges=1===g(a.useroundedges),z=y?1:0,y=y?0:1,p=l.use3DLighting=1===g(a.use3dlighting,1),m=H({},h.tooltip.style),q=new Ja(this.colorPaletteMap,(0<a.palette&&6>a.palette?a.palette:g(this.paletteIndex,1))-1),n=c(a.basefont,"Verdana,sans"),w=Ea(a.basefontsize,10),s=c(a.basefontcolor,q.basefontcolor),u=Ea(a.outcnvbasefontsize,
w),v=c(a.outcnvbasefont,n),t=u+"px",E=aa(c(a.outcnvbasefontcolor,s)),F=c(a.bgcolor,a.canvasbgcolor,q.canvasbgcolor),r=c(a.bgalpha,a.canvasbgalpha,q.canvasbgalpha),G=g(a.usevaluesformarkers,e.markers&&e.markers.items&&e.markers.items.length,!(e.markers&&e.markers.application&&e.markers.application.length&&e.markers.definition&&e.markers.definition.length)),B,C,L,I,A,M,D,w=w+"px",s=aa(s);this.realtimeEnabled&&this.postHCJSONCreation&&this.postHCJSONCreation.call(this,h);l.events.click=this.linkClickFN;
k.numberFormatter=this.numberFormatter;H(k,{width:b,height:d,showTooltip:g(a.showtooltip,this.showtooltip,1),showHoverEffect:g(a.showhovereffect,1),tooltipSepChar:c(a.tooltipsepchar,", "),showValues:g(a.showvalues,this.showValues,1),showCanvasBG:c(a.showcanvasbg,1),useValuesForMarkers:G,adjustViewPortForMarkers:g(a.adjustviewportformarkers,G),flatScrollBars:g(a.flatscrollbars,0),scrollBar3DLighting:g(a.scrollbar3dlighting,1),outCanvasStyle:{fontFamily:v,color:E,fontSize:t},inCanvasStyle:{fontFamily:n,
fontSize:w,color:s}});fa(k.outCanvasStyle);B=fa(k.inCanvasStyle);k.trendStyle=k.outCanvasStyle;"0"==k.showCanvasBG&&(r="0");C=c(a.entitybordercolor,a.bordercolor,q.plotbordercolor);L=c(a.entityfillcolor,a.fillcolor,q.plotfillcolor);I=c(a.entityfillalpha,a.fillalpha,q.plotfillalpha);A=c(a.entityfillratio,a.fillratio,q.plotfillratio);M=c(a.entityfillangle,a.fillangle,q.plotfillangle);D=c(a.nullentityfillcolor,a.nullentitycolor,L);G=g(a.showcanvasborder,y)?g(a.canvasborderthickness,1):0;H(h,{chart:{emulateFlashGutter:g(a._emulateflashgutter,
1),defaultSeriesType:this.defaultSeriesType,paletteIndex:q.index,borderRadius:g(a.canvasborderradius,0),borderColor:W(c(a.canvasbordercolor,q.canvasbordercolor),c(a.canvasborderalpha,q.canvasborderalpha)),borderWidth:G,borderDashStyle:g(a.canvasborderdashed,0)?Fa(g(a.canvasborderdashlen,4),g(a.canvasborderdashgap,2),G):"none",backgroundColor:P({color:F,alpha:r,angle:c(a.bgangle,a.canvasbgangle,q.canvasbgangle),ratio:c(a.bgratio,a.canvasbgratio,q.canvasbgratio)}),plotBorderColor:"#ffffff",plotBorderWidth:0,
plotBackgroundColor:P({color:"#ffffff",alpha:0}),bgSWF:c(a.bgimage,a.bgswf),bgSWFAlpha:g(a.bgimagealpha,a.bgswfalpha,100),bgImageScale:g(a.bgimagescale,100),bgImageDisplayMode:c(a.bgimagedisplaymode,"none").toLowerCase(),logoURL:ra(a.logourl),logoPosition:c(a.logoposition,"tl").toLowerCase(),logoAlpha:g(a.logoalpha,100),logoLink:ra(a.logolink),logoScale:g(a.logoscale,100),logoLeftMargin:g(a.logoleftmargin,0),logoTopMargin:g(a.logotopmargin,0),toolbar:function(){var e={button:{}},f=e.button,h;f.scale=
g(a.toolbarbuttonscale,1.15);f.width=g(a.toolbarbuttonwidth,15);f.height=g(a.toolbarbuttonheight,15);f.radius=g(a.toolbarbuttonradius,2);f.spacing=g(a.toolbarbuttonspacing,5);f.fill=W(c(a.toolbarbuttoncolor,"ffffff"));f.labelFill=W(c(a.toolbarlabelcolor,"cccccc"));f.symbolFill=W(c(a.toolbarsymbolcolor,"ffffff"));f.hoverFill=W(c(a.toolbarbuttonhovercolor,"ffffff"));f.stroke=W(c(a.toolbarbuttonbordercolor,"bbbbbb"));f.symbolStroke=W(c(a.toolbarsymbolbordercolor,"9a9a9a"));f.strokeWidth=g(a.toolbarbuttonborderthickness,
1);f.symbolStrokeWidth=g(a.toolbarsymbolborderthickness,1);h=f.symbolPadding=g(a.toolbarsymbolpadding,5);f.symbolHPadding=g(a.toolbarsymbolhpadding,h);f.symbolVPadding=g(a.toolbarsymbolvpadding,h);h=e.position=c(a.toolbarposition,"tr").toLowerCase();switch(h){case "tr":case "tl":case "br":case "bl":break;default:h="tr"}f=e.hAlign="left"===(""+a.toolbarhalign).toLowerCase()?"l":h.charAt(1);h=e.vAlign="bottom"===(""+a.toolbarvalign).toLowerCase()?"b":h.charAt(0);e.hDirection=g(a.toolbarhdirection,"r"===
f?-1:1);e.vDirection=g(a.toolbarvdirection,"b"===h?-1:1);e.vMargin=g(a.toolbarvmargin,6);e.hMargin=g(a.toolbarhmargin,10);e.x=g(a.toolbarx,"l"===f?0:b);e.y=g(a.toolbary,"t"===h?0:d);return e}()},title:{text:ha(a.caption),offsetX:Number(a.captionxshift),offsetY:Number(a.captionyshift),position:c(a.captionposition,void 0!==a.captionxshift||void 0!==a.captionyshift?"top left":"top"),padding:g(a.captionpadding,10),style:{fontFamily:c(a.captionfontfamily,v),color:c(a.captionfontcolor,E).replace(/^#?([a-f0-9]+)/ig,
"#$1"),fontSize:g(a.captionfontsize,u+3)+"px",fontWeight:0===g(a.captionfontbold)?"normal":"bold"}},subtitle:{text:ha(a.subcaption),style:{fontFamily:c(a.subcaptionfontfamily,a.captionfontfamily,v),color:c(a.subcaptionfontcolor,a.captionfontcolor,E).replace(/^#?([a-f0-9]+)/ig,"#$1"),fontSize:g(a.subcaptionfontsize,g(qa(a.captionfontsize-3,1),u))+"px",fontWeight:0===g(a.subcaptionfontbold)?"normal":"bold"}},orphanStyles:{defaultStyle:{style:H({},k.inCanvasStyle)}},tooltip:{enabled:0!==k.showTooltip,
style:{fontFamily:n,fontSize:w,lineHeight:B,color:s,padding:g(a.tooltippadding,this.tooltippadding,3)+"px",backgroundColor:W(c(m.backgroundColor,a.tooltipbgcolor,q.tooltipbgcolor),c(a.tooltipbgalpha,"100")),borderColor:W(c(m.borderColor,a.tooltipbordercolor,q.tooltipbordercolor),c(a.tooltipborderalpha,"100")),borderWidth:g(a.tooltipborderthickness,y)+"px",borderRadius:g(a.tooltipborderradius,z+1)+"px"},constrain:g(a.constraintooltip,1),shadow:g(a.showtooltipshadow,a.showshadow,1)?{enabled:!0,opacity:qa(g(a.tooltipbgalpha,
100),g(a.tooltipborderalpha,100))/100}:!1},legend:{itemStyle:{fontFamily:c(a.legenditemfont,v),fontSize:g(a.legenditemfontsize,u)+"px",color:aa(c(a.legenditemfontcolor,E)),fontWeight:g(a.legenditemfontbold)?"bold":"normal"},itemHiddenStyle:{fontFamily:v,fontSize:t,color:aa(c(a.legenditemhiddencolor,E))},itemHoverStyle:{color:aa(c(a.legenditemhoverfontcolor,a.legenditemfontcolor,E))},enabled:g(a.showlegend,1),title:{text:ha(a.legendcaption),style:{fontFamily:c(a.legendcaptionfont,v),fontSize:g(a.legendcaptionfontsize,
u)+"px",color:aa(c(a.legendcaptionfontcolor,E)),fontWeight:g(a.legendcaptionfontbold,1)?"bold":"normal"},align:Q[c(a.legendcaptionalignment)]},position:c(a.legendposition,0===g(e.colorrange&&e.colorrange.gradient,0)?"right":"bottom"),backgroundColor:c(a.legendbgcolor,q.bgcolor),backgroundAlpha:c(a.legendbgalpha,"100"),borderColor:c(a.legendbordercolor,q.legendbordercolor),borderThickness:c(a.legendborderthickness,"1"),borderAlpha:c(a.legendborderalpha,"100"),shadow:g(a.legendshadow,1),allowDrag:g(a.legendallowdrag,
0),scroll:{scrollBgColor:c(a.legendscrollbgcolor,a.scrollcolor,"AAAAAA"),scrollBtnColor:c(a.legendscrollbtncolor,"BBBBBB"),scrollBarColor:c(a.legendscrollbarcolor,"CCCCCC")},reversed:g(a.reverselegend,0),interactive:g(a.interactivelegend,0),minColor:D,lighting3d:p},markers:{dataLabels:{style:{fontFamily:c(a.markerfont,n),fontSize:g(a.markerfontsize,parseInt(w,10)),fontColor:c(a.markerfontcolor,s)}},showTooltip:g(a.showmarkertooltip,k.showTooltip),showLabels:g(a.showmarkerlabels,a.showlabels,1),showHoverEffect:g(a.showmarkerhovereffect,
1),labelPadding:c(a.markerlabelpadding,"5"),labelWrapWidth:g(a.markerlabelwrapwidth,0),labelWrapHeight:g(a.markerlabelwrapheight,0),fillColor:c(a.markerfillcolor,a.markerbgcolor,q.markerfillcolor),fillAlpha:c(a.markerfillalpha,q.markerfillalpha),fillAngle:c(a.markerfillangle,q.markerfillangle),fillRatio:c(a.markerfillratio,q.markerfillratio),fillPattern:c(a.markerfillpattern,q.markerbgpattern),hoverFillColor:a.markerfillhovercolor,hoverFillAlpha:a.markerfillhoveralpha,hoverFillRatio:a.markerfillhoverratio,
hoverFillAngle:a.markerfillhoverangle,borderThickness:c(a.markerborderthickness,1),borderColor:c(a.markerbordercolor,q.markerbordercolor),borderAlpha:g(a.markerborderalpha,q.markerborderalpha),hoverBorderThickness:a.markerborderhoverthickness,hoverBorderColor:a.markerborderhovercolor,hoverBorderAlpha:a.markerborderhoveralpha,radius:g(a.markerradius&&x.trimString(a.markerradius),7),shapeId:c(a.defaultmarkershape,"circle"),labelSepChar:c(a.labelsepchar,", "),tooltipSepChar:k.tooltipSepChar,autoScale:g(a.autoscalemarkers,
0),tooltext:c(f&&f.tooltext,a.markertooltext),dataEnabled:k.useValuesForMarkers,valueToRadius:g(a.markerradiusfromvalue,1),valueMarkerAlpha:c(a.valuemarkeralpha,"75"),hideNull:g(a.hidenullmarkers,0),nullRadius:g(a.nullmarkerradius,a.markerradius,7),adjustViewPort:g(a.adjustviewportformarkers,0),startAngle:g(a.markerstartangle,90),maxRadius:g(a.maxmarkerradius,0),minRadius:g(a.minmarkerradius,0),applyAll:g(a.applyallmarkers,0),shadow:g(a.showmarkershadow,a.showshadow,0)},connectors:{showHoverEffect:g(a.showconnectorhovereffect,
1),thickness:g(a.connectorthickness,a.markerconnthickness,"2"),color:c(a.connectorcolor,a.markerconncolor,q.markerbordercolor),alpha:c(a.connectoralpha,a.markerconnalpha,"100"),hoverthickness:g(a.connectorhoverthickness,a.connectorthickness,a.markerconnthickness,"2"),hovercolor:c(a.connectorhovercolor,a.connectorcolor,a.markerconncolor,q.markerbordercolor),hoveralpha:c(a.connectorhoveralpha,a.connectoralpha,a.markerconnalpha,"100"),dashed:g(a.connectordashed,a.markerconndashed,0),dashLen:g(a.connectordashlen,
a.markerconndashlen,3),dashGap:g(a.connectordashgap,a.markerconndashgap,2),font:c(a.connectorfont,a.markerconnfont,n),fontColor:c(a.connectorfontcolor,a.markerconnfontcolor,s),fontSize:g(a.connectorfontsize,a.markerconnfontsize,parseInt(w,10)),showLabels:g(a.showconnectorlabels,a.showmarkerlabels,a.showlabels,1),labelBgColor:c(a.connectorlabelbgcolor,a.markerconnlabelbgcolor,q.plotfillcolor),labelBorderColor:c(a.connectorlabelbordercolor,a.markerconnlabelbordercolor,q.markerbordercolor),shadow:g(a.showconnectorshadow,
a.showmarkershadow,a.showshadow,0),showTooltip:g(a.showconnectortooltip,a.showmarkertooltip,k.showTooltip),tooltext:c(f&&f.connectortooltext,a.connectortooltext),hideOpen:g(a.hideopenconnectors,1)},entities:{baseScaleFactor:this.baseScaleFactor,dataLabels:{style:{fontFamily:n,fontSize:w,lineHeight:B,color:h.plotOptions.series.dataLabels.color=s}},fillColor:L,fillAlpha:I,fillRatio:A,fillAngle:M,borderColor:C,borderAlpha:c(a.entityborderalpha,a.borderalpha,this.borderAlpha,"100"),borderThickness:g(a.showentityborder,
a.showborder,1)?g(a.entityborderthickness,a.borderthickness,1):0,scaleBorder:g(a.scaleentityborder,a.scaleborder,0),hoverFillColor:c(a.entityfillhovercolor,a.hoverfillcolor,a.hovercolor,q.plothoverfillcolor),hoverFillAlpha:c(a.entityfillhoveralpha,a.hoverfillalpha,a.hoveralpha,q.plothoverfillalpha),hoverFillRatio:c(a.entityfillhoverratio,a.hoverfillratio,a.hoverratio,q.plothoverfillratio),hoverFillAngle:c(a.entityfillhoverangle,a.hoverfillangle,a.hoverangle,q.plothoverfillangle),hoverBorderThickness:c(a.entityborderhoverthickness,
a.hoverborderthickness),hoverBorderColor:c(a.entityborderhovercolor,q.plotbordercolor),hoverBorderAlpha:c(a.entityborderhoveralpha,q.plotborderalpha),nullEntityColor:D,nullEntityAlpha:c(a.nullentityfillalpha,a.nullentityalpha,I),nullEntityRatio:c(a.nullentityfillratio,a.nullentityratio,A),nullEntityAngle:c(a.nullentityfillangle,a.nullentityangle,M),connectorColor:c(a.labelconnectorcolor,a.connectorcolor,s),connectorAlpha:c(a.labelconnectoralpha,a.connectoralpha,"100"),connectorThickness:g(a.labelconnectorthickness,
a.borderthickness,1),showHoverEffect:g(a.showentityhovereffect,a.usehovercolor,k.showHoverEffect),hoverOnNull:g(a.hoveronnull,a.entityhoveronnull,1),labelPadding:g(a.labelpadding,5),showLabels:g(a.showlabels,1),labelsOnTop:g(a.entitylabelsontop,1),includeNameInLabels:g(a.includenameinlabels,1),includeValueInLabels:g(a.includevalueinlabels,0),useSNameInTooltip:g(a.usesnameintooltip,0),useShortName:g(a.usesnameinlabels,1),labelSepChar:c(a.labelsepchar,", "),showTooltip:g(a.showentitytooltip,k.showTooltip),
tooltipSepChar:k.tooltipSepChar,tooltext:a.entitytooltext,hideNullEntities:g(a.hidenullentities,0),showHiddenEntityBorder:g(a.showhiddenentityborder,1),showNullEntityBorder:g(a.shownullentityborder,1),hiddenEntityColor:c(a.hiddenentitycolor,a.hiddenentityfillcolor,a.hiddenentityalpha||a.hiddenentityfillalpha?D:"ffffff"),hiddenEntityAlpha:c(a.hiddenentityalpha,a.hiddenentityfillalpha,.001),shadow:g(a.showshadow,this.defaultPlotShadow,q.shadow)},entitydef:{useSNameAsId:g(a.usesnameasid,0)}});h.legend.title.style.lineHeight=
fa(h.legend.title.style);h.legend.itemStyle.lineHeight=fa(h.legend.itemStyle);h.legend.itemHiddenStyle.lineHeight=fa(h.legend.itemHiddenStyle);f=Da(b,d,a.markermaxradius,a.markerminradius);h.markers.maxRadius=f.max;h.markers.minRadius=f.min;a.tooltipcolor&&(h.tooltip.style.color=ka(a.tooltipcolor));void 0!==c(a.clickurl)&&(l.link=a.clickurl,l.style.cursor="pointer",pa&&(l.style._cursor="hand"),h.plotOptions.series.point.events.click=function(){l.events.click.call({link:a.clickurl})});f=l.bgImageDisplayMode;
k=ra(a.bgimagevalign,"").toLowerCase();z=ra(a.bgimagehalign,"").toLowerCase();"tile"==f||"fill"==f||"fit"==f?("top"!=k&&"middle"!=k&&"bottom"!=k&&(k="middle"),"left"!=z&&"middle"!=z&&"right"!=z&&(z="middle")):("top"!=k&&"middle"!=k&&"bottom"!=k&&(k="top"),"left"!=z&&"middle"!=z&&"right"!=z&&(z="left"));l.bgImageVAlign=k;l.bgImageHAlign=z;this.parseStyles(h);fa(h.title.style);fa(h.subtitle.style);fa(h.tooltip.style);h.plotOptions.series.allowPointSelect=!0;this.parseExportOptions(h);this.preSeriesAddition&&
this.preSeriesAddition(h,e,b,d);this.series&&this.series(e,h,this.name,b,d);this.postSeriesAddition&&this.postSeriesAddition(h,e,b,d);this.spaceManager(h,e,b,d);ca.console&&ca.FC_DEV_ENVIRONMENT&&ca.console.log(h);return h},series:function(b,d){function e(b){for(C=b&&b.length||0;C--;)v=b[C],r=v.value,v.cleanValue=a.getCleanValue(r),v.formattedValue=null!==v.cleanValue?a.dataLabels(r):void 0,v.origValue=r,null!==v.cleanValue&&(s=S(v.cleanValue,s),u=qa(v.cleanValue,u))}function h(a,b,e){for(C=a&&a.length||
0;C--;){v=a[C];var f;a:{f=g(v.value);for(var h=void 0,l=void 0,h=void 0,m=F&&F.length||0;m--;)if(h=F[m],l=Number(h.maxvalue),h=g(h.minvalue,d.colorRange.scaleMin),f>=h&&f<=l){f=m;break a}f=null}G=f;null!==G&&(D="gradient"===A.type?d.colorRange.getColorObj(v.value).code:q&&q[G]&&c(q[G].color,q[G].code),w[G]||(w[G]=[]),D&&(v.color=v.color?v.color:D,b&&(v.alpha=v.alpha?v.alpha:b),e&&(p||v.fillhoveralpha||(v.fillhoveralpha=v.alpha),k||v.fillhovercolor||(v.fillhovercolor=v.color)),w[G].push(v)))}}var a=
this.numberFormatter,f=this.hcJSON.series,l=d.markers.valueMarkerAlpha,k=d.markers.hasHoverColor,p=d.markers.hasHoverAlpha,m=this.dataObj,n=d[ga],t=m.colorrange,q=t&&t.color,A=d.legend,w={},t={legendClick:function(){var a;if(a=this.chart)!this.legend&&(this.legend=this.plot.legend),a.legendClick(this,!this.visible)},getEventArgs:function(){var a;if(a=this.chart)return!this.legend&&(this.legend=this.plot.legend),a.getEventArgs(this)},setVisible:function(a){var b=this.data,c=this.legendItem,d=this.visible;
this.visible=a=void 0===a?!d:a;c&&A.colorizeItem&&A.colorizeItem(this,a);for(d=b&&b.length;d--;)(c=b[d].mapItem)&&(a?c.show&&c.show():c.hide&&c.hide())}},s=Infinity,u=-Infinity,v,D,E,F,r,G,B,C;e(m.data||[]);n.useValuesForMarkers&&e(m.markers&&m.markers.items||[]);n._doNotShowLegend=!0;A.type=m.colorrange&&"1"===m.colorrange.gradient?"gradient":"point";Infinity===s&&(s=void 0);-Infinity===u&&(u=void 0);n.dataMin=s;n.dataMax=u;d.colorRange=new x.colorRange({colorRange:m.colorrange,dataMin:s,dataMax:u,
defaultColor:A.minColor,numberFormatter:a});C=(F=d.colorRange.colorArr)&&F.length||0;if(0<C){for(;C--;)E=F[C],!n._doNotShowLegend||""===E.label&&void 0===E.label||(n._doNotShowLegend=!1),f.push(H({type:this.defaultSeriesType,showInLegend:!0,data:[],plot:{},name:E.label,color:E.code,rangeMin:E.minvalue,rangeMax:E.maxvalue,visible:!0},t));h(m.data||[]);n.useValuesForMarkers&&h(m.markers&&m.markers.items||[],l,!0);f=f.reverse();for(B in w)f[B]&&(f[B].data=w[B])}else f.push({type:this.defaultSeriesType,
data:[]});n._doNotShowLegend&&(this.hcJSON.legend.enabled=!1)},preliminaryScaling:function(b,c){for(var e=c.markers&&c.markers.items||[],h=e&&e.length||0,a=Infinity,f=Infinity,g=-Infinity,k=-Infinity,l,m;h--;)m=e[h],l=Number(m.x),m=Number(m.y),a=S(a,l),f=S(f,m),g=qa(g,l),k=qa(k,m);return{x:a,y:f,x1:g,y1:k}},getScalingParameters:function(b,c,e,h){var a=b/c,f=e/(b*this.baseScaleFactor),g=h/(c*this.baseScaleFactor),k=0,l=0;f>g?(f=g,k+=(e-h*a)/2,b=200/(c*f)):(l+=(h-e/a)/2,b=200/(b*f));return{scaleFactor:f,
strokeWidth:b,translateX:k,translateY:l}},calculateMarkerBounds:function(b,c,e,h,a){var f=b.markers,g=b[ga];b=g.dataMin;for(var g=g.dataMax,k=f.minRadius,l=f.maxRadius,m=f.hideNull,n=f.nullRadius,f=f.valueToRadius,p=(c=c.markers&&c.markers.items||[],c.length)||0,q=Infinity,t=Infinity,w=-Infinity,s=-Infinity,u,v,x;p--;)v=c[p],null!==v.cleanValue?(f&&void 0===v.radius&&(v.radius=k+(l-k)*(v.cleanValue-b)/(g-b)),x=Number(v.radius),u=(Number(v.x)+h)*e,v=(Number(v.y)+a)*e,q=S(q,u-x),t=S(t,v-x),w=qa(w,u+
x),s=qa(s,v+x)):m?v.__hideMarker=!0:void 0===v.radius&&(v.radius=n);return{x:q,y:t,x1:w,y1:s}},spaceManager:function(b,c,e,h){var a=b.chart,f=b[ga],g=a.spacingLeft,k=a.spacingTop,l=this.baseWidth,m=this.baseHeight;e-=a.spacingRight+g;a=h-(a.spacingBottom+k);h=f._captionBlock=this.manageTitleSpace(b,c,e,a);var n=f._legendBlock=this.placeLegendBlock(b,c,e,a-h.height,h.isBottom?h.height:0);e-=n.width;var a=a-h.height-n.height,p=n=0;f.useValuesForMarkers?(f.adjustViewPortForMarkers?(f=this.preliminaryScaling(b,
c),f.x1>l&&(l=f.x1),0>f.x&&(l+=-f.x,p=-f.x),f.y1>m&&(m=f.y1),0>f.y&&(m+=-f.y,n=-f.y),f=this.getScalingParameters(l,m,e,a),f=this.calculateMarkerBounds(b,c,f.scaleFactor*this.baseScaleFactor,p,n),b=a,c=e,0>f.x&&(g+=-f.x,e+=f.x),0>f.y&&(k+=-f.y,a+=f.y),f.x1>c&&(e-=f.x1-c),f.y1>b&&(a-=f.y1-b)):(f=this.getScalingParameters(l,m,e,a),this.calculateMarkerBounds(b,c,f.scaleFactor*this.baseScaleFactor,p,n)),f=this.getScalingParameters(l,m,e,a),g+=p*f.scaleFactor*this.baseScaleFactor,k+=n*f.scaleFactor*this.baseScaleFactor):
f=this.getScalingParameters(l,m,e,a);/bottom/i.test(h.position)||(k+=h.height);this.scaleFactor=f.scaleFactor;this.strokeWidth=f.strokeWidth;this.translateX=f.translateX+g;this.translateY=f.translateY+k},placeGLegendBlockRight:x.placeGLegendBlockRight,placeGLegendBlockBottom:x.placeGLegendBlockBottom,placeLegendBlock:function(b,c,e,h,a){var f=b.legend,g=b[ga],k=f.position.toLowerCase(),l={position:k};if("0"===c.chart.showlegend||g._doNotShowLegend)return l.height=0,l.width=0,l;"bottom"===k?(l.height=
"gradient"===f.type?this.placeGLegendBlockBottom(b,c,e,h):this.placeLegendBlockBottom(b,c,e,h),l.width=0,a&&(f.y=-a)):(e/=2,l.width="gradient"===f.type?this.placeGLegendBlockRight(b,c,e,h):this.placeLegendBlockRight(b,c,e,h),l.height=0);return l},manageTitleSpace:function(b,c,e,h){var a=this.hcJSON;b=a.title;c=a.chart;var a=a.subtitle,f=this.smartLabel,g=h/2,k=0,l=b.position.toLowerCase(),m=b.padding,n=!1,p=b.offsetX,q=b.offsetY,t=0,w={},s,u;if(""===b.text&&""===a.text)return{height:0,position:l};
isNaN(p)&&isNaN(q)||(n=!0,p=isNaN(p)?0:p,q=isNaN(q)?0:q);s=b.text;if(""!==s){f.setStyle(b.style);u=f.getOriSize(s);if(u.width>e||u.height>g)u=f.getSmartText(s,e,g),b.text=u.text,u.tooltext&&(b.originalText=u.tooltext);b.height=t=u.height;k+=t}g-=k;s=a.text;if(""!==s){f.setStyle(a.style);u=f.getOriSize(s);if(u.width>e||u.height>g)u=f.getSmartText(s,e,g),a.text=u.text,u.tooltext&&(a.originalText=u.tooltext);k+=a.height=u.height}k=k+m>g?g:k+m;l.match(/left/)?(a.align=b.align="start",a.x=b.x=c.marginLeft):
l.match(/right/)?(a.align=b.align="end",a.x=b.x=e):(a.align=b.align="middle",a.x=b.x=e/2);/bottom/.test(l)?(e=h-k+c.marginTop+m,b.y=e,a.y=e+t,n?(b.y+=q,a.y+=q,b.x+=p,a.x+=p):(c.marginBottom+=k,w.isBottom=!0)):n?(b.y+=q,a.y+=q,b.x+=p,a.x+=p):c.marginTop+=k;w.height=n?0:k;w.position=l;return w},getFirstId:function(){return this.firstEntity},getEntityPaths:function(b){var c={},e=this.entities,h;if(b){for(h in e)c[h]=e[h];return c}return e},redefineEntities:function(b,c){var e=this.entities,h={},a={},
f=0,g,k,l,m,n,p,q,t;for(q=b.length;q--;)if(g=b[q],k=g.internalid,n=g.newid?g.newid:k,l=g.sname,g=g.lname,m=e[k],k=x.trimString(k),n=x.trimString(n),m){h[n]=n={origId:k};a[k]=!0;for(p in m)n[p]=m[p];n.shortLabel=l?l:m.shortLabel;n.label=g?g:m.label}this.entities={};for(t in h)h[t].origId=t,this.entities[t.toLowerCase()]=h[t],f+=1;for(t in e)if(n=e[t],t=x.trimString(t),!a[t]){c.useSNameAsId?(this.entities[n.shortLabel.toLowerCase()]=m={},m.origId=n.shortLabel):(this.entities[t.toLowerCase()]=m={},m.origId=
t);for(p in n)m[p]=n[p];f+=1}this.entityCount=f},colorPaletteMap:{basefontcolor:"foregroundcolor",bordercolor:"foregrounddarkcolor",borderalpha:"foregrounddarkalpha",bgcolor:"backgroundlightcolor",bgalpha:"backgroundlightalpha",bgangle:"backgroundlightangle",bgratio:"backgroundlightratio",canvasbordercolor:"foregrounddarkcolor",canvasborderalpha:"foregrounddarkalpha",canvasbgcolor:"backgroundlightcolor",canvasbgalpha:"backgroundlightalpha",canvasbgangle:"backgroundlightangle",canvasbgratio:"backgroundlightratio",
tooltipbordercolor:"foregrounddarkcolor",tooltipborderalpha:"foregrounddarkalpha",tooltipbgcolor:"backgroundlightcolor",tooltipbgalpha:"backgroundlightalpha",tooltipfontcolor:"foregroundcolor",legendbordercolor:"foregrounddarkcolor",legendborderalpha:"foregrounddarkalpha",markerbordercolor:"foregroundlightcolor",markerborderalpha:"foregroundlightalpha",markerfillcolor:"backgrounddarkcolor",markerfillalpha:"backgrounddarkalpha",markerfillangle:"backgrounddarkangle",markerfillratio:"backgrounddarkratio",
plotfillcolor:"backgroundcolor",plotfillalpha:"backgroundalpha",plotfillangle:"backgroundangle",plotfillratio:"backgroundratio",plothoverfillcolor:"backgrounddarkcolor",plothoverfillalpha:"backgrounddarkalpha",plothoverfillangle:"backgrounddarkangle",plothoverfillratio:"backgrounddarkratio",plotbordercolor:"foregroundcolor",plotborderalpha:"foregroundalpha",shadow:"shadow"},eiMethods:{getMapName:function(){return this.jsVars.hcObj.logic.name},getEntityList:function(){var b=this.jsVars.hcObj,b=b.entities&&
b.entities.items,c,e=[],h,a;for(h in b)a=b[h],c=a.eJSON,e.push({id:a.id,originalId:a.originalId||a.id,label:c.label,shortlabel:c.shortLabel,value:a.value,formattedValue:a.formattedValue,toolText:a.toolText});return e},getDataAsCSV:function(){var b=this.jsVars,b=b.hcObj&&b.hcObj.entities&&b.hcObj.entities.items,c='"Id","Short Name","Long Name","Value","Formatted Value"',e,h,a,f;for(e in b)h=b[e],a=h.eJSON,f=h.value,c+='\r\n"'+h.id+'","'+a.shortLabel+'","'+a.label+'","'+(void 0===f?"":f)+'","'+h.formattedValue+
'"';return c},getMapAttribute:function(){var b=this.jsVars.fcObj;Z.raiseWarning(this,"12061210581","run","JavaScriptRenderer~getMapAttribute()",'Use of deprecated "getMapAttribute()". Replace with "getChartAttribute()".');return b.getChartAttribute.apply(b,arguments)},exportMap:function(){var b=this.jsVars.fcObj;Z.raiseWarning(this,"12061210581","run","JavaScriptRenderer~exportMap()",'Use of deprecated "exportMap()". Replace with "exportChart()".');return b.exportChart&&b.exportChart.apply(b,arguments)},
addMarker:function(b){this.jsVars.hcObj.markers.addMarkerItem(b)||Z.raiseWarning(this,"1309264086","run","MapsRenderer~addMarker()","Failed to add marker. Check the options and try again.")},updateMarker:function(b,c){var e=this.jsVars.hcObj,h=e.markers,e=e.mapAnnotations,a;b&&(b=(b+"").toLowerCase(),h=h.items[b])&&(a=h.options,H(a,c),h=h.draw().markerShape,e.update(b,h))},removeMarker:function(b){var c=this.jsVars.hcObj.markers,e;b&&(b=(b+"").toLowerCase(),(e=c.items[b])&&e.destroy(),delete c.items[b])}}},
X.linebase);X("renderer.maps",{drawGraph:function(){var b=this,c=b.logic.chartInstance,e=b.paper,h=b.layers,a,f,g;b.options.nativeMessage||(h.dataset||(h.dataset=e.group("dataset").insertAfter(h.background),h.tracker=e.group("hot").insertAfter(h.dataset)),b.shadowLayer||(b.shadowLayer=h.shadow=e.group("shadow").insertBefore(h.dataset)),h.dataset&&h.dataset.hide(),h.shadow&&h.shadow.hide(),b.strokeWidth=b.logic.strokeWidth,a=b.logic.scaleFactor,b.translateX=f=b.logic.translateX,b.translateY=g=b.logic.translateY,
b.sFactor=a*b.logic.baseScaleFactor,b.transformStr=["t",f,",",g,"s",a,",",a,",0,0"].join(""),b.options.tooltip&&!1!==b.options.tooltip.enabled&&e.tooltip(b.options.tooltip.style,b.options.tooltip.shadow,b.options.tooltip.constrain),b.mapAnnotations=new x.Annotations,b.mapAnnotations.reset(null,{id:"geo",showbelow:0,autoscale:0,grpxshift:b.translateX?b.translateX:0,grpyshift:b.translateY?b.translateY:0,xscale:100*(b.sFactor?b.sFactor:1),yscale:100*(b.sFactor?b.sFactor:1),options:{useTracker:!0}}),
b.processEntityDefs(),b.drawEntities(),c.addEventListener("internal.mapdrawingcomplete",function(a){a.detachHandler();la&&(h.dataset&&h.dataset.attr({transform:b.transformStr}),h.shadow&&h.shadow.attr({transform:b.transformStr}));h.dataset&&h.dataset.show();h.shadow&&h.shadow.show()}),b.drawMarkers())},setScaleRange:function(b,c){for(var e=this.options.series,g=e.length,a,f,l,k;g--;)if(l=e[g],f=(a=l.data)&&a.length)if(l.rangeMin>=b&&l.rangeMax<=c)l.setVisible(!0);else if(l.rangeMax<b||l.rangeMin>
c)l.setVisible(!1);else for(;f--;)l=(k=a[f].mapItem)&&k.value,isNaN(l)||""===l||(l>=b&&l<=c?k.show():k.hide())},processEntityDefs:function(){var b=this.logic,c=this.options.series,e=c&&c.length;for(b.redefineEntities(b.dataObj.entitydef||[],this.options.entitydef);e--;)c[e].chart=this},drawEntities:function(){this.entities=new n(this.logic&&this.logic.dataObj&&this.logic.dataObj.data,this,this.logic,this.layers.dataset)},drawMarkers:function(){var b=this.logic&&this.logic.dataObj&&this.logic.dataObj.markers||
null;b&&(this.markers=new A(b,this,this.group));this.options.entities.labelsOnTop||this.entities.drawLabels()},checkComplete:function(){var b=this.logic,c=b.chartInstance;this.entities&&this.entities.isReady()&&(this.mapAnnotations.draw(this),b.hasRendered=!0,Z.raiseEvent("internal.mapdrawingcomplete",{renderer:this},c))}},X["renderer.root"])},[3,2,0,"release"]]);
