/*
 FusionCharts JavaScript Library - Tree Map Chart
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @version 3.10.1
*/
FusionCharts.register("module",["private","modules.renderer.js-treemap",function(){function G(b){return b?b.replace(/^#*/,"#"):"#E5E5E5"}function n(b,h){this.label=b;this.value=parseFloat(h,10);this.prev=this.next=void 0;this.meta={}}function F(){this._b=[];this._css=void 0;this.rangeOurEffectApplyFn=function(){};this.statePointerLow={value:void 0,index:void 0};this.statePointerHigh={value:void 0,index:void 0}}var s=this.hcLib,L=s.extend2,N=s.chartAPI,S=s.Raphael,O=s.chartAPI,H=s.graphics,K=H.convertColor,
P=H.getLightColor,y=this.raiseEvent,T=s.colorRange,I,E,w=s.pluckNumber,t=s.pluck,H=!/fusioncharts\.com$/i.test(this.window.location.hostname);S.addSymbol({backIcon:function(b,h,a){--a;var c=h+a,f=c-a/2,g=b+a,e=f-a;return["M",b,h-a,"L",b-a,h,b,c,b,f,g,f,g,e,g-a,e,"Z"]},homeIcon:function(b,h,a){--a;var c=2*a,f=b-a,g=f+c/6,e=h+a,d=g+c/4,v=e-a/2,m=d+c/6,A=v+a/2,k=m+c/4,l=A-a;return["M",b,h-a,"L",f,h,g,h,g,e,d,e,d,v,m,v,m,A,k,A,k,l,k+c/6,l,"Z"]}});Array.prototype.indexOf||(Array.prototype.indexOf=function(b,
h){var a;if(null==this)throw new TypeError('"this" is null or not defined');var c=Object(this),f=c.length>>>0;if(0===f)return-1;a=+h||0;Infinity===Math.abs(a)&&(a=0);if(a>=f)return-1;for(a=Math.max(0<=a?a:f-Math.abs(a),0);a<f;){if(a in c&&c[a]===b)return a;a++}return-1});"function"!=typeof Object.create&&(Object.create=function(){function b(){}var h=Object.prototype.hasOwnProperty;return function(a){var c,f,g;if("object"!=typeof a)throw TypeError("Object prototype may only be an Object or null");
b.prototype=a;c=new b;b.prototype=null;if(1<arguments.length)for(g in f=Object(arguments[1]),f)h.call(f,g)&&(c[g]=f[g]);return c}}());Function.prototype.bind||(Function.prototype.bind=function(b){if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var h=Array.prototype.slice.call(arguments,1),a=this,c=function(){},f=function(){return a.apply(this instanceof c?this:b,h.concat(Array.prototype.slice.call(arguments)))};this.prototype&&
(c.prototype=this.prototype);f.prototype=new c;return f});n.prototype.constructor=n;n.prototype.addChild=function(b){b instanceof n&&(this.next=this.next||[],[].push.call(this.next,b),b.setParent(this));return this.next};n.prototype.getChildren=function(){return this.next};n.prototype.setParent=function(b){b instanceof n&&(this.prev=b);return this};n.prototype.getSiblingCount=function(){var b;if(this instanceof n&&(b=this.getParent()))return b.getChildren().length};n.prototype.getParent=function(){return this.prev};
n.prototype.getLabel=function(){return this.label};n.prototype.getValue=function(){return this.value};n.prototype.getSibling=function(b){b=b.toLowerCase();var h=this.getParent(),a=this.getLabel(),c,f;if(h)for(h=h.getChildren(),c=0;c<h.length;c++)if(f=h[c],f=f.getLabel(),f===a)switch(b){case "left":return h[c-1];case "right":return h[c+1]}};n.prototype.setMeta=function(b,h){this.meta[b]=h};n.prototype.getMeta=function(b){return b?this.meta[b]:this.meta};F.prototype.constructor=F;F.prototype.setRangeOutEffect=
function(b,h){this._css=b;this.rangeOurEffectApplyFn=h};F.prototype.addInBucket=function(b){var h=this._b,a=b.getValue(),c=0,f=h.length-1;a:{for(var g,e;c<=f;)if(g=(c+f)/2|0,e=h[g],e=e.getValue(),e<a)c=g+1;else if(e>a)f=g-1;else{a=g;break a}a=~f}h.splice(Math.abs(a),0,b)};F.prototype.moveLowerShadePointer=function(b){var h=this._b,a,c,f,g=this.statePointerLow;a=g.index;c=g.value;var e=!1;a=void 0!==a?a:0;c=void 0!==c?c:Number.NEGATIVE_INFINITY;if(b!==c){if(c<=b){for(;;){f=(c=h[a++])?c.getValue():
0;if(b<f||!c)break;e=!0;c.rangeOutEffect=this._css;this.rangeOurEffectApplyFn.call(c,this._css)}a=e?a-2:a-1}else{for(;;){f=(c=h[a--])?c.getValue():0;if(b>=f||!c)break;c.cssConf=c.cssConf||{};e=!0;delete c.rangeOutEffect;c.cssConf.opacity=1;this.rangeOurEffectApplyFn.call(c,c.cssConf)}a=e?a+2:a+1}g.index=a;g.value=b}};F.prototype.moveHigherShadePointer=function(b){var h=this._b,a=h.length,c,f,g=this.statePointerHigh;f=g.index;c=g.value;var e=!1,a=void 0!==f?f:a-1;c=void 0!==c?c:Number.POSITIVE_INFINITY;
if(b!==c){if(c>b){for(;;){f=(c=h[a--])?c.getValue():0;if(b>=f||!c)break;e=!0;c.rangeOutEffect=this._css;this.rangeOurEffectApplyFn.call(c,this._css)}a=e?a+2:a+1}else{for(;;){f=(c=h[a++])?c.getValue():0;if(b<f||!c)break;c.cssConf=c.cssConf||{};e=!0;delete c.rangeOutEffect;c.cssConf.opacity=1;this.rangeOurEffectApplyFn.call(c,c.cssConf)}a=e?a-2:a-1}g.index=a;g.value=b}};N("treemap",{friendlyName:"Tree Map Chart",rendererId:"treemap",standaloneInit:!0,defaultSeriesType:"treemap",creditLabel:H,series:function(b,
h){var a=b&&b.data||[],c=h.chart,f={data:a},g={},e=this.dataObj.chart,d=this.hcJSON.chart;a&&a.length&&(h.series.push(f),c.metaTreeInf=g,this.hcJSON.legend.enabled=!1,a=this.dataObj.chart.algorithm||"sliceanddice",d.algorithm=a.toLowerCase(),d.horizontalPadding=w(e.horizontalpadding,5),d.horizontalPadding=0>d.horizontalPadding?0:d.horizontalPadding,d.verticalPadding=w(e.verticalpadding,5),d.verticalPadding=0>d.verticalPadding?0:d.verticalPadding,d.showParent=w(e.showparent,1),d.highlightParentsOnHover=
w(e.highlightparentsonhover,0),d.defaultParentBGColor=t(e.defaultparentbgcolor,void 0),d.baseFontSize=w(e.basefontsize,10),d.baseFontSize=1>d.baseFontSize?1:d.baseFontSize,d.labelFontSize=w(e.labelfontsize,void 0),d.labelFontSize=1>d.labelFontSize?1:d.labelFontSize,d.baseFont=t(e.basefont,"Verdana, Sans"),d.labelFont=t(e.labelfont,void 0),d.baseFontColor=t(e.basefontcolor,"#000000").replace(/^#?([a-f0-9]+)/ig,"#$1"),d.labelFontColor=t(e.labelfontcolor,void 0),d.labelFontColor&&(d.labelFontColor=d.labelFontColor.replace(/^#?([a-f0-9]+)/ig,
"#$1")),d.labelFontBold=w(e.labelfontbold,0),d.labelFontItalic=w(e.labelfontitalic,0),d.plotBorderThickness=w(e.plotborderthickness,1),d.plotBorderThickness=0>d.plotBorderThickness?0:5<d.plotBorderThickness?5:d.plotBorderThickness,d.plotBorderColor=t(e.plotbordercolor,"#000000").replace(/^#?([a-f0-9]+)/ig,"#$1"),d.tooltipSeparationCharacter=t(e.tooltipsepchar,","),d.parentLabelLineHeight=w(e.parentlabellineheight,12),d.parentLabelLineHeight=0>d.parentLabelLineHeight?0:d.parentLabelLineHeight,d.labelGlow=
w(e.labelglow,1),d.labelGlowIntensity=w(e.labelglowintensity,100)/100,d.labelGlowIntensity=0>d.labelGlowIntensity?0:1<d.labelGlowIntensity?1:d.labelGlowIntensity,d.labelGlowColor=t(e.labelglowcolor,"#ffffff").replace(/^#?([a-f0-9]+)/ig,"#$1"),d.labelGlowRadius=w(e.labelglowradius,2),d.labelGlowRadius=0>d.labelGlowRadius?0:10<d.labelGlowRadius?10:d.labelGlowRadius,a=w(e.showlegend,1),d.btnResetChartTooltext=t(e.btnresetcharttooltext,"Back to Top"),d.btnBackChartTooltext=t(e.btnbackcharttooltext,"Back to Parent"),
d.rangeOutBgColor=t(e.rangeoutbgcolor,"#808080").replace(/^#?([a-f0-9]+)/ig,"#$1"),d.rangeOutBgAlpha=w(e.rangeoutbgalpha,100),d.rangeOutBgAlpha=1>d.rangeOutBgAlpha||100<d.rangeOutBgAlpha?100:d.rangeOutBgAlpha,e=b.colorrange||{},d=w(e.mapbycategory,0),h.colorRange=new T({colorRange:e,mapByCategory:d,numberFormatter:this.numberFormatter}),h.colorRange.rangeOutsideColor=e.rangeoutsidecolor,h.legend.type="gradient",h.legend.enabled=!!a)},placeLegendBlockRight:function(){return"gradient"===arguments[0].legend.type?
s.placeGLegendBlockRight?s.placeGLegendBlockRight.apply(this,arguments):0:s.placeLegendBlockRight.apply(this,arguments)},placeLegendBlockBottom:function(){return"gradient"===arguments[0].legend.type?s.placeGLegendBlockBottom?s.placeGLegendBlockBottom.apply(this,arguments):0:s.placeLegendBlockBottom.apply(this,arguments)}},N.singleseries);E=function(){function b(a,c){this.node=a;this.bucket=c?new F:void 0}var h;b.prototype.get=function(){var a=this.order,c=this.bucket;return function g(b){var d,v,
m;m=["label","value","data"];var A;if(b)for(A in d=new n(b.label,b.value),v=b.data||[],0===v.length&&c&&c.addInBucket(d),b)-1===m.indexOf(A)&&d.setMeta(A,b[A]);a&&(v=a(v));for(b=0;b<v.length;b++)m=v[b],m=g(m),d.addChild(m);return d}(this.node)};b.prototype.getBucket=function(){return this.bucket};h=function(){function a(){this.con={}}var c={},b;a.prototype.constructor=a;a.prototype.get=function(a){return this.con[a]};a.prototype.set=function(a,c){this.con[a]=c};return{getInstance:function(g){var e;
return(e=c[g])?b=e:b=c[g]=new a}}}();return{AbstractTreeMaker:b,iterator:function(a){function c(a){this.iterAPI=a}var b;c.prototype.constructor=c;c.prototype.initWith=function(a){return this.iterAPI(a)};b=(new c(function(a){var c=a,b=[],f=!1;b.push(c);return{next:function(){var a,c,k;if(!f)return c=b.shift(),(k=(a=c.getChildren())&&a.length||0)&&[].unshift.apply(b,a),0===b.length&&(f=!0),c},reset:function(){f=!1;c=a;b.length=0;b.push(c)}}})).initWith(a);a=(new c(function(a){var c=a,b=[],f=[],m=!1;
b.push(c);f.push(c);return{next:function(){var a,c,f;if(!m)return c=b.shift(),(f=(a=c.getChildren())&&a.length||0)&&[].push.apply(b,a),0===b.length&&(m=!0),c},nextBatch:function(){var a,c;if(!m)return a=f.shift(),(c=(a=a.getChildren())&&a.length||0)&&[].push.apply(f,a),0===b.length&&(m=!0),a},reset:function(){m=!1;c=a;b.length=0;b.push(c)}}})).initWith(a);return{df:b,bf:a}},initConfigurationForlabel:function(a,c,b){var g=a.x,e=a.y,d=c/2,h=b.showParent?0:1;return function(a,A){var k=!1,l={x:void 0,
y:void 0,width:void 0,height:void 0},q={},B=0,C={},z={},D,p;p=a.meta;if(a)return a.next||(k=!0),q.label=a.getLabel(),l.width=A.width-2*g,l.x=A.x+A.width/2,C=A.height-2*e,!k&&C<c&&(l.height=-1),k?(l.height=l.height?l.height:A.height-2*e,l.y=A.y+A.height/2):h?(l.y=-1,c=e=0,D="hidden"):(l.height=l.height?l.height:c,l.y=A.y+e+d),B+=2*e,B+=c,q.rectShiftY=B,q.textRect=l,b.labelGlow?(z["stroke-width"]=b.labelGlowRadius,z.opacity=b.labelGlowIntensity,z.stroke=b.labelGlowColor,z.visibility="hidden"===D?"hidden":
"visible"):z.visibility="hidden",C={fontSize:b.labelFontSize||b.baseFontSize,fontFamily:b.labelFont||b.baseFont,fill:p&&p.fontcolor&&G(p.fontcolor)||b.labelFontColor||b.baseFontColor,fontWeight:b.labelFontBold&&"bold",fontStyle:b.labelFontItalic&&"italic",visibility:D},{conf:q,attr:C,highlight:z}}},context:h,mapColorManager:function(a,b){var f=a.defaultParentBGColor,f=G(f);return function(g){var e={},d=g.meta,d=d.fillcolor?G(d.fillcolor):void 0;e.fill=g.next?d||f:d||b.getColorObj(g.getValue()).code&&
"#"+b.getColorObj(g.getValue()).code||G(b.rangeOutsideColor);e.stroke=a.plotBorderColor;e.strokeWidth=a.plotBorderThickness;return e}},abstractEventRegisterer:function(a){var b=a[1],f=b.logic,g=b.logic.chartInstance,e=f.hcJSON.legend,d=f.hcJSON.chart,h=a[0].drawTree,m=a[3].removeLayers;b.backToParent=function(f){var k=this,e=k&&k.getParent();f?y("beforedrillup",{node:k,withoutHead:!d.showParent},g,void 0,function(){e&&(m(),h.apply(e,a));y("drillup",{node:k,sender:b.fusionCharts,withoutHead:!d.showParent,
drillUp:b.backToParent,drillUpToTop:b.resetTree},g);k=k&&k.getParent()},function(){y("drillupcancelled",{node:k,withoutHead:!d.showParent},g)}):(e&&(m(),h.apply(e,a)),k=k&&k.getParent())};b.resetTree=function(f){for(var e=this,l=e&&e.getParent(),q;l;)q=l,l=l.getParent();f?y("beforedrillup",{node:e,withoutHead:!d.showParent},g,void 0,function(){q&&(m(),h.apply(q,a),y("drillup",{node:e,sender:b.fusionCharts,withoutHead:!d.showParent,drillUp:b.backToParent,drillUpToTop:b.resetTree},g))},function(){y("drillupcancelled",
{node:e,withoutHead:!d.showParent},g)}):q&&(m(),h.apply(q,a))};return function(f,k){var l=f.virginNode,q,B,C;if(B=l.getParent()){if(l===k)C=B,q="drillup";else{if(l.next)C=l;else if(C=B,k===C){q=void 0;return}q="drilldown"}e.enabled&&s.rendererRoot.resetLegendSlider();q&&y("before"+q,{node:C,withoutHead:!d.showParent},g,void 0,function(){m();h.apply(C,a);y(q,{node:C,sender:b.fusionCharts,withoutHead:!d.showParent,drillUp:b.backToParent,drillUpToTop:b.resetTree},g)},function(){y(q+"cancelled",{node:C,
withoutHead:!d.showParent},g)});b.backToParent=b.backToParent.bind(C);b.resetTree=b.resetTree.bind(C)}}}}}();I=function(){function b(){c.apply(this,arguments)}function h(){var b=a[f],c;c=Array.prototype.slice.call(arguments,0);c.unshift(b);b.drawTree.apply(e,c)}var a,c=E.AbstractTreeMaker,f,g,e,d;a={sliceanddice:{orderNodes:function(){return this.sort(function(b,a){return parseFloat(b.value,10)<parseFloat(a.value,10)?1:-1})},areaBaseCalculator:function(b,a){return function(c,d,e){var f,h,g={},z,D,
p,r=f=0;if(c){e&&(f=e.textMargin||f);r=f;e=c.getParent();f=c.getSibling("left");if(e){h=e.getValue();p=e.rect;z=p.height-2*a-r;D=p.width-2*b;g.effectiveRect={height:z,width:D,x:p.x+b,y:p.y+a+r};g.effectiveArea=z*D;g.ratio=c.getValue()/h;if(f)return d.call(c,g,f,e);g.lastIsParent=!0;return d.call(c,g,e)}return null}}},applyShadeFiltering:function(b,a){var c=this;c.setRangeOutEffect(b,a);return function(b){c.moveLowerShadePointer(b.start);c.moveHigherShadePointer(b.end)}},drawTree:function(b,a,c,d){var e=
arguments,f=a.logic,g=d.drawRect,h=d.drawText,z=d.drawHot,D=c.horizontalPadding,p=c.verticalPadding,r=a.smartLabel,s=E.iterator,Q=s(this).df,u,w=b.areaBaseCalculator(D,p),x=a.logic.hcJSON.chart,n=x.highlightParentsOnHover,t,y,R=E.context,M=E.mapColorManager(x,f.hcJSON.colorRange),U=E.abstractEventRegisterer(e),f=f.chartInstance.jsVars._reflowData;t=E.initConfigurationForlabel({x:5,y:5},x.parentLabelLineHeight,x);for(e=u=Q.next();e.getParent();)e=e.getParent();e!=u?(a.resetButton.show(),a.backButton.show()):
(a.resetButton.hide(),a.backButton.hide());r.setStyle({fontSize:(x.labelFontSize||x.baseFontSize)+"px",fontFamily:x.labelFont||x.baseFont,lineHeight:1.2*(x.labelFontSize||x.baseFontSize)+"px"});f.tree=u;a.backToParent=a.backToParent.bind(u);a.resetTree=a.resetTree.bind(u);(function V(a,b){var c,d,e,f,m;d={};var k,l={},q={};e={};a&&(c=a.rect={},e=a.textRect={},c.width=b.width,c.height=b.height,c.x=b.x,c.y=b.y,e=M(a),k=g(c,e),a.cssConf=e,f=t(a,c),m=f.conf,d.textMargin=m.rectShiftY,e=m.textRect,m=r.getSmartText(m.label,
e.width,e.height).text,h(m,e,f.attr,f.highlight),a.plotItem=k,l.virginNode=a,l.plotItem=k,l.toolText=a.getLabel()+x.tooltipSeparationCharacter+a.getValue(),l.rect=c,q.hover=[function(){var a,b,c;c=R.getInstance("hover");b=this.virginNode;a=n&&!b.next?(a=b.getParent())?a:b:this.virginNode;c.set("element",a);c=K(P(a.cssConf.fill,80),60);a.plotItem.tracker.attr({fill:c})}.bind(l),function(){var a,b;a=R.getInstance("hover").get("element");b=K(a.cssConf.fill||"#fff",0);a.plotItem.tracker.attr({fill:b})}.bind(l)],
q.tooltip=[l.toolText],q.click=[function(){U(this,u)}.bind(l)],z(l,q),c=Q.next(),d=w(c,function(a,b){var c=a.effectiveArea*a.ratio,e=a.effectiveRect,d=b.rect,f,m,g;a.lastIsParent?(m=e.x,g=e.y,f=e.height,e=e.width,y=this.isDirectionVertical=!0):(f=e.height+e.y-(d.height+d.y),e=e.width+e.x-(d.width+d.x),y=this.isDirectionVertical=!b.isDirectionVertical);y?(e=c/f,m=void 0!==m?m:d.x,g=void 0!==g?g:d.y+d.height):(f=c/e,m=void 0!==m?m:d.x+d.width,g=void 0!==g?g:d.y);return{height:f,width:e,x:m,y:g}},d),
V(c,d))})(u,c)}},squarified:{orderNodes:function(){return this.sort(function(a,b){return parseFloat(a.value,10)<parseFloat(b.value,10)?1:-1})},areaBaseCalculator:function(a,b){return function(c,e,d){var f={},g,h=g=0,z,D;if(c&&0!==c.length)return d&&(g=d.textMargin||g),h=g,z=c[0],(c=z.getParent())?(D=c.rect,d=D.height-2*b-h,g=D.width-2*a,f.effectiveRect={height:d,width:g,x:D.x+a,y:D.y+b+h},f.effectiveArea=d*g,e.call(z,f,c)):null}},layoutManager:function(){function a(b,c){this.totalValue=c;this._rHeight=
b.height;this._rWidth=b.width;this._rx=b.x;this._ry=b.y;this._rTotalArea=b.height*b.width;this.nodes=[];this._prevAR=void 0;this._rHeight<this._rWidth&&(this._hSegmented=!0)}a.prototype.constructor=a;a.prototype.addNode=function(a){var b=this._rTotalArea,c,e,d,f,g,h,v,p=this._hSegmented,r=this._rx,s=this._ry,w,u,n,x,t=0;this.nodes.push(a);d=0;for(e=this.nodes.length;d<e;d++)t+=parseFloat(this.nodes[d].getValue(),10);c=t/this.totalValue*b;p?(b=this._rHeight,e=c/b,w=r+e,u=s,n=this._rHeight,x=this._rWidth-
e):(e=this._rWidth,b=c/e,w=r,u=s+b,n=this._rHeight-b,x=this._rWidth);d=0;for(f=this.nodes.length;d<f;d++)a=this.nodes[d],g=a.getValue(),h=g/t*c,a.hRect=a.rect||{},a._hRect=a._rect||{},g=a.rect={},p?(g.width=v=e,g.height=v=h/v,g.x=r,g.y=s,s+=v):(g.height=v=b,g.width=v=h/v,g.x=r,g.y=s,r+=v),h=Math.max(g.height,g.width),g=Math.min(g.height,g.width),a.aspectRatio=h/g;if(1<this.nodes.length){if(this.prevAR<a.aspectRatio){this.nodes.pop().rect={};d=0;for(e=this.nodes.length;d<e;d++)this.nodes[d].rect=1===
e&&this.nodes[d].firstPassed?this.nodes[d]._hRect:this.nodes[d].hRect,p=this.nodes[d]._rect={},r=this.nodes[d].rect,p.width=r.width,p.height=r.height,p.x=r.x,p.y=r.y;return!1}}else a&&(p=a._rect={},r=a.rect,p.width=r.width,p.height=r.height,p.x=r.x,p.y=r.y,a.firstPassed=!0);this.prevAR=a.aspectRatio;this.height=b;this.width=e;this.getNextLogicalDivision=function(){return{height:n,width:x,x:w,y:u}};return a};return{RowLayout:a}}(),applyShadeFiltering:function(a,b){var c=this;c.setRangeOutEffect(a,
b);return function(a){c.moveLowerShadePointer(a.start);c.moveHigherShadePointer(a.end)}},drawTree:function(a,b,c,d){var e=arguments,f=b.logic,g=a.areaBaseCalculator(c.horizontalPadding,c.verticalPadding),h=a.layoutManager.RowLayout,s=b.smartLabel,w=d.drawRect,p=d.drawText,r=d.drawHot,n=E.iterator,n=n(this).bf,t,u=b.logic.hcJSON.chart,y=u.highlightParentsOnHover,x,F=E.context,I=E.mapColorManager(u,f.hcJSON.colorRange),J=E.abstractEventRegisterer(e),e=f.chartInstance.jsVars._reflowData;x=E.initConfigurationForlabel({x:5,
y:5},u.parentLabelLineHeight,u);for(f=t=n.next();f.getParent();)f=f.getParent();f!=t?(b.resetButton.show(),b.backButton.show()):(b.resetButton.hide(),b.backButton.hide());s.setStyle({fontSize:(u.labelFontSize||u.baseFontSize)+"px",fontFamily:u.labelFont||u.baseFont,lineHeight:1.2*(u.labelFontSize||u.baseFontSize)+"px"});e.tree=t;b.backToParent=b.backToParent.bind(t);b.resetTree=b.resetTree.bind(t);(function M(a,b){var c,d,e,f,m=0,k,l,v;k={};var q;l={};var n={};d={};if(a&&(c=a.rect={},d=a.textRect=
{},c.width=b.width,c.height=b.height,c.x=b.x,c.y=b.y,d=I(a),f=w(c,d),a.cssConf=d,q=x(a,c),v=q.conf,k.textMargin=v.rectShiftY,d=v.textRect,v=s.getSmartText(v.label,d.width,d.height).text,p(v,d,q.attr,q.highlight),a.plotItem=f,l.virginNode=a,l.plotItem=f,l.toolText=a.getLabel()+u.tooltipSeparationCharacter+a.getValue(),l.rect=c,n.hover=[function(){var a,b,c;c=F.getInstance("hover");b=this.virginNode;a=y&&!b.next?(a=b.getParent())?a:b:this.virginNode;c.set("element",a);c=K(P(a.cssConf.fill,80),60);a.plotItem.tracker.attr({fill:c})}.bind(l),
function(){var a,b;a=F.getInstance("hover").get("element");b=K(a.cssConf.fill||"#fff",0);a.plotItem.tracker.attr({fill:b})}.bind(l)],n.tooltip=[l.toolText],n.click=[function(){J(this,t)}.bind(l)],r(l,n),e=a.getChildren()))for(k=g(e,function(a,b){var c,d,f=0,g,k,l=[];c=new h({width:a.effectiveRect.width,height:a.effectiveRect.height,x:a.effectiveRect.x,y:a.effectiveRect.y},b.getValue());for(d=e.length;f++!==d;)g=e[f-1],k=c.addNode(g),!1===k?(c=c.getNextLogicalDivision(),c=new h(c,b.getValue()-m),f--):
(m+=parseFloat(g.getValue(),10),l.push(g));return l},k),c=0,f=k.length;c<f;c++)l=k[c],M(l,l.rect)})(t,c)}}};b.prototype=Object.create(c.prototype);b.prototype.constructor=c;b.prototype.order=function(b){var c=a[f];return c.orderNodes.apply(b,[c])};return{init:function(a,b){f=a;d=b},plotOnCanvas:function(a,c){g=new b(a,d);e=g.get();return h},applyShadeFiltering:function(b,c){var d,e;e=a[f].applyShadeFiltering.call(g.getBucket(),b,c);return function(a){d=Array.prototype.slice.call(arguments,0);d.unshift(a);
e.apply(g.getBucket(),d)}},setTreeBase:function(a){return a&&(e=a)}}}();O("renderer.treemap",{drawPlotTreemap:function(){var b=this,h=b.paper,a=b.layers,c=b.definition.data,f=b.logic,g=f.hcJSON.chart,e=f.hcJSON.legend,d=b.toolbar,n=g.animation,m=n&&n.duration||void 0,n=g.algorithm,t=f.hcJSON.legend.enabled,k,f=b.options.chart.metaTreeInf,l=a.tracker,q=a.dataset=a.dataset||h.group("dataset"),B=a.datalabels=a.datalabels||h.group("datalabels").insertAfter(q),C=a.lineHot=a.lineHot||h.group("line-hot",
l),z=a.labelHighlight=a.labelHighlight||h.group("labelhighlight",B),D=a.floatLabel=a.floatLabel||h.group("labelfloat",B).insertAfter(z),p,r=[],y=[],E=[],u=[],a={},F,x,G,B=b.fusionCharts.jsVars._reflowData,H,J,l={hcJSON:{chart:{chartResized:!0,rawAnimationDuration:1E3*w(b.definition.chart.animationduration/2,.5)}}};f.effectiveWidth=b.canvasRight-b.canvasLeft;f.effectiveHeight=b.canvasBottom-b.canvasTop;f.startX=b.canvasLeft;f.startY=b.canvasTop;F=f.effectiveWidth/2;x=f.effectiveHeight/2;b.resetButton=
d.add("homeIcon",function(){e.enabled&&s.rendererRoot.resetLegendSlider();b.resetTree&&b.resetTree(!0)},{tooltip:g.btnResetChartTooltext}).hide();k=b.resetButton.attr("fill");k[2]="rgba(255,255,255,0)";b.resetButton.attr("fill",[k[0],k[1],k[2],k[3]]);k=b.resetButton.attr("stroke");k[1]="rgba(136,136,136)";b.resetButton.attr("stroke",[k[0],k[1]]);b.backButton=d.add("backIcon",function(){e.enabled&&s.rendererRoot.resetLegendSlider();b.backToParent&&b.backToParent(!0)},{tooltip:g.btnBackChartTooltext}).hide();
k=b.backButton.attr("fill");k[2]="rgba(255,255,255,0)";b.backButton.attr("fill",[k[0],k[1],k[2],k[3]]);k=b.backButton.attr("stroke");k[1]="rgba(136,136,136)";b.backButton.attr("stroke",[k[0],k[1]]);a.drawRect=function(a,b){var c,d,e={},f={};for(c in a)d=a[c],0>d&&(a[c]=0,f.visibility="hidden");m||H&&(m=g.rawAnimationDuration)?(L(e,a),e.x=F,e.y=x,e.height=0,e.width=0,p=h.rect(e,q).css(b),p.animate(a,m,"normal")):p=h.rect(a,q).css(b);p.css(f);r.push(p);return p};a.drawText=function(a,b,c,d){var e={},
f=h.text(D),k=h.text(z);L(e,c);delete e.fill;e["stroke-linejoin"]="round";m||H&&(m=g.rawAnimationDuration)?(f.attr({text:a,x:F,y:x,fill:"#000000"}).css(c),f.animate({text:a,x:b.x,y:b.y},m,"normal"),k.attr({text:a,x:F,y:x,stroke:"#ffffff"}).css(e).css(d),k.animate({x:b.x,y:b.y},m,"normal")):(f.attr({text:a,x:b.x,y:b.y,fill:"#000000"}).css(c),k.attr({text:a,x:b.x,y:b.y,stroke:"#ffffff"}).css(e).css(d));y.push(f);E.push(k);return f};a.drawHot=function(a,b){var c;c=a.plotItem;var d=a.rect,e,f,g;for(f in d)g=
d[f],0>g&&(d[f]=0);c=c.tracker=h.rect(C).attr(d).attr({cursor:"pointer",fill:"rgba(255, 255, 255, 0)",stroke:"none"});for(e in b)d=b[e],c[e].apply(c,d);u.push(c);return c};a.removeLayers=function(){var a,b,c,d,e,f;b=Math.max(r.length,y.length,E.length,u.length);for(a=0;a<b;a++)c=r[a],d=y[a],f=u[a],e=E[a],c&&c.remove(),d&&d.remove(),f&&f.remove(),e&&e.remove();r.length=0;y.length=0;u.length=0};(d=B.tree)?(c=B.drawTreeFn,J=!0):(B.algorithmAPI=I.init(n,t),B.drawTreeFn=c=I.plotOnCanvas(c[0]),J=!1);I.setTreeBase(d);
e.enabled&&(G=I.applyShadeFiltering({fill:g.rangeOutBgColor,opacity:.01*g.rangeOutBgAlpha},function(a){this.plotItem&&this.plotItem.attr(a)}),b.setScaleRange=function(a,b){var c={start:a,end:b};J&&G({start:Number.NEGATIVE_INFINITY,end:Number.POSITIVE_INFINITY});G(c)});c.apply(void 0,[b,{width:f.effectiveWidth,height:f.effectiveHeight,x:f.startX,y:f.startY,horizontalPadding:g.horizontalPadding,verticalPadding:g.verticalPadding},a]);g.chartResized&&(H=!0);L(b.logic.chartInstance.jsVars._reflowData,
l,!0)}},O["renderer.root"])}]);
